<?php
/*echo 'This is view of Paginator';
echo $this->currentUrl;*/
	
	$rw=new Zendvn_View_Helper_CmsRewriteLink();
	
	$arrValue=array();
	$arrValue['name']=$rw->noSign($this->objView->arrParam['name']);
	$arrValue['id']=$this->objView->arrParam['id'];
	$arrValue['cat_name']=$rw->noSign($this->objView->arrParam['cat_name']);
	$arrValue['cat_id']=$this->objView->arrParam['cat_id'];
	$this->currentUrl	= $this->objView->serverUrl($this->objView->url($arrValue,'product-index-list'));



	$linkStart 		= $this->currentUrl . '/page' . $this->first.'.html';
	
	$linkPrevious = '#';
	if(isset($this->previous)){
		$linkPrevious 	= $this->currentUrl . '/page' . $this->previous.'.html';
	}
	$linkNext = '#';
	if(isset($this->next)){
		$linkNext 		= $this->currentUrl . '/page' . $this->next.'.html';
	}
	
	$linkEnd 		= $this->currentUrl . '/page' . $this->last.'.html';
	
	$strPage  = '';
	foreach ($this->pagesInRange as $key){
		if($this->current == $key){
	
			$strPage .= '<li class="current">'.$key.'</li>';
		}else{
			$linkPage = $this->currentUrl . '/page' . $key.'.html';
			$strPage .= '<li class="countitem"><a href="' . $linkPage . '" title="trang ' . $key .'">' . $key .'</a></li>'; 
		}
	}

	$page = 'Page ' . $this->current .' Of ' . $this->last;
?>



<div class="limiter">
</div>

<div class="pages">
<strong>Trang:</strong>
<ol>	
	<?php if($linkPrevious!='#') { ?><li class="previous i-previous"><a id="prev_test" href="<?php echo $linkPrevious;?>"><img src="<?php echo $this->objView->imgUrl;?>/i_pager-prev.gif" alt="Prev" class="v-middle" /></a></li><?php }?>
<?php echo $strPage;?>
    <?php if($linkNext!='#') { ?><li class="next i-next"><a id="next_test" href="<?php echo $linkNext;?>"><img src="<?php echo $this->objView->imgUrl;?>/i_pager-next.gif" alt="Next" class="v-middle" /></a></li><?php }?>
</ol>




