<?php
    $auth = Zend_Auth::getInstance();
    $infoAuth = $auth->getIdentity();
    echo $infoAuth->user_id;
?>
<div class="clear"></div>
<div id="wrapper">
    <div id="content">
        <div id="content-left">
            <div id="left-content">
                <div id="scriptolution-soft-post" class="scriptolution-soft-box static">
                    <?php
                        if($infoAuth->user_id)
                        {
                    ?>
                    <div class="head">
                        <ul class="switch">
                        	<li class="tab_photo current"><a class="photo" href="<?php echo $this->baseUrl('dang-anh.shock')?>">Ảnh</a></li>
                        	<li class="tab_video"><a class="video" href="<?php echo $this->baseUrl('dang-video.shock')?>">Video</a></li>
        					<li class="tab_blog"><a class="blog" href="<?php echo $this->baseUrl('dang-truyen-cuoi.shock')?>">Truyện cười</a></li>
        					<li class="tab_tamsu"><a class="blog" href="<?php echo $this->baseUrl('dang-tam-su.shock')?>">Tâm sự</a></li>
        					<li class="tab_tinnong"><a class="blog" href="<?php echo $this->baseUrl('dang-bao-hay.shock')?>">Báo hay</a></li>
                        </ul>
                    </div>
                    <?php }?>
                    <?php
                        if($this->errors)
                        {
                            foreach($this->errors as $v)
                            {
                                echo $v;
                            }
                        }
                        if(!$infoAuth->user_id)
                        {
                            echo '<Br><br><br><p class="form-message error">VUI LÒNG ĐĂNG NHẬP TRƯỚC KHI ĐĂNG ẢNH. BẤM <a style="color:white; text-decoration:underline" href="'.$this->baseUrl('dang-nhap.shock').'">VÀO ĐÂY</a> ĐỂ ĐĂNG NHẬP</p><br><br><br>';
                        }
                        else
                        {
                    ?>
                    <div class="clear"></div>
                    <div class="content form_photo">
                        <form id="form-scriptolution-soft-post-image" class="modal" action="#" enctype="multipart/form-data" method="post">
                            <h3>Đăng ảnh</h3>
                                <?php
                                     if($this->arrParam['t'] == 'link')
                                     {
                                ?>
                                <div class="field">
                                    <label>
                                        <h4>Link ảnh <span style="color: red;">(*)</span></h4>                        
                                        <input id="photo_post_url" type="text" class="text" name="url" value="" style="display:block;">
                                    </label>
                                    <p class="info"><a class="upload_photo" href="<?php echo $this->baseUrl('dang-anh.shock')?>"><strong style="color: #E92E6C;">Tải từ máy tính.</strong></a> Các định dạng được cho phép là JPEG, GIF or PNG.</p>
                                    <input type="hidden" name="type" value="link" />
                                </div>
                                <?php
                                    }
                                    else
                                    {
                                ?>
                                <div class="field">
                                    <label>
                                        <h4>File ảnh <span style="color: red;">(*)</span></h4>                            
                                        <input id="photo_file_upload" class="file text " type="file" name="image" style="display:block;">
                                    </label>
                                	<p class="info"><a class="upload_photo" href="<?php echo $this->baseUrl('dang-anh.shock?t=link')?>"><strong style="color: #E92E6C;">Sử dụng link  có sẵn.</strong></a> Các định dạng được cho phép là JPEG, GIF or PNG.</p>
                                    <input type="hidden" name="type" value="file" />
                                </div>
                                <?php
                                    }
                                ?>
                                <div class="field">
                                <label>
                                    <h4>Tiêu đề ảnh  <span style="color: red;">(*)</span></h4>
                                    <input id="post_title" type="text" class="text tipped" name="title" maxlength="120" value="">
                                    <p class="info">Tiêu đề hay sẽ giúp nhiều thành viên sẽ câu được lượt xem và like đấy ^_^.</p>
                                </label>
                            </div>
                            <div class="field">
                                <label>
                                    <h4>Nguồn</h4>
                                    <input type="text" class="text tipped" name="source" value="" maxlength="300">
                                    <p class="info">Hãy tông trọng sự sáng tạo của tác giả nào.</p>
                                </label>                    
                            </div>
                            <hr>
                            <div class="field checkbox">
                            	<label for="submit-nsfw">
                            	<input id="submit-nsfw" type="checkbox" class="checkbox" name="is_adult" value="1">Bài này dành cho người trên 18 tuổi</label>
                            </div>                
                    </div>
                
                
                    <div class="actions">
                        <ul>
                            <!--li class="loading-btn" style="visibility:hidden"><a class="button loading"></a></li>
                            <li class="form-btn"><a class="cancel" href="/">Huỷ</a></li>
                            <li class="form-btn"><a class="button send" id="ekle">Đăng hình</a></li-->
                            <li style="float: right;"><input class="buttons" type="submit" name="submit" value="Đăng hình" /></li>
                            <li style="float: right;margin-right:10px;"><input class="buttons" type="reset" name="reset" value="Hủy" /></li>
                        </ul>
                    </div>
        			</form>
        			<script type="text/javascript">
                    /*$('input').each(function()
        			{
                    	$(this).focus(function()
        				{
                    		$(this ).next('.info').css('visibility','visible');
                    	})
                    	$(this).blur(function()
        				{
                    		$(this).next('.info').css('visibility','hidden');
                    	})
                    });
                    $('#ekle').click(function(){
                    	$('#form-scriptolution-soft-post-image').submit();
                    });*/
                    </script>
                    <?php
                        }
                    ?>
                </div>
            </div>
        </div>
        <div id="content-right">
            <div id="side-bar">
                <?php echo $this->ShowSidebar($this,'noiquy');?>
            </div>    
        </div>
    </div>
</div>