<!--Main conent-->
    <div id="baseDiv">
        <!--Search-->            
        <?php $this->showSearch($this);?>
        <!--end search-->
        
        <div class="index_border_M">
            <!--Title cateogry -->
            <div class="title_page">
                <div class="title_page_L"></div>
                <div class="title_page_Ce">MUA SẮM - THỜI TRANG</div>
                <div class="title_page_R"></div>
            </div>
            <!--End title category-->
            <br class="clean" />
            <!--End Title category-->
            <div class="product_detail">
            <!--Product detail left-->
                <div class="detail_L">
                    <!--Category Detail-->
                        <h1 class="product_detail_TT">Amme Fashion</h1>
                        <!--Slide images-->
                        <div id="silde_images">
                			<img src="images/new-ribbon.png" width="112" height="112" alt="New Ribbon" id="ribbon">
                			<div id="slides">
                				<div class="slides_container">
                					<a href="#"  target="_blank"><img src="images/simple/slide/1.jpg" width="610" height="330" alt="Slide 1"></a>
                					<a href="#" target="_blank"><img src="images/simple/slide/2.jpg" width="610" height="330" alt="Slide 2"></a>
                					<a href="#" target="_blank"><img src="images/simple/slide/3.jpg" width="610" height="330" alt="Slide 3"></a>
                					<a href="#" target="_blank"><img src="images/simple/slide/4.jpg" width="610" height="330" alt="Slide 4"></a>
                					<a href="#" target="_blank"><img src="http://slidesjs.com/examples/standard/img/slide-5.jpg" width="610" height="330" alt="Slide 5"></a>
                				</div>
                				<!--a href="#" class="prev"><img src="images/arrow-prev.png" width="24" height="43" alt="Arrow Prev"></a>
                				<a href="#" class="next"><img src="images/arrow-next.png" width="24" height="43" alt="Arrow Next"></a-->
                			</div>
                			<img src="images/example-frame.png" width="630" height="400" alt="Example Frame" id="frame" />
                		</div>
                        <!--End slide images-->
                        <!--Dieu kien su dung-->
                        <div class="condition">
                            <div class="condition_T">
                            </div>
                            <div class="condition_Co">
                                <ul class="condition_L">
                                    <li>Thiết kế trẻ trung, thanh lịch, sang trọng, tinh tế.</li>
            <li>Đội ngũ nhân viên chuyên nghiệp và am hiểu thời trang, sẵn sàng phục vụ và tư vấn tận tình để giúp bạn tìm được bộ cánh ưng ý nhất.</li>
            <li>Chất liệu cao cấp như: voan, lụa, phi, cotton trên nền màu sắc và hoa văn tinh tế.</li>
            <li>Cập nhật liên tục các sản phẩm mới.</li>
            <li>Tham khảo: <a target="blank" href="/Uploads//AgentContent/ammefashion/bang%20gia.jpg"><b>Giá</b></a></li>
                                </ul>
                                <ul class="condition_R">
                                        <li>Giới hạn sử dụng 1 Thẻ / 1 hóa đơn</li>
                                        <li>Không tách / cộng gộp hóa đơn nếu đi nhóm nhiều người</li>
                                        <li>Không dùng chung với các khuyến mãi hoặc ưu đãi khác</li>                           
                                    
                                    <li>Thời gian hoạt động từ: 10h30 đến 21h30.</li>
            <li>Được dùng vào các ngày lễ.</li>
            <li><b><font color="#FF0000">Giảm 40% trên tổng hóa đơn.</font></b/></li>
                                    
                                </ul>
                                <br class="clean" />
                            </div>
                            <div class="condition_B">
                            </div>
                        </div>
                        <!--End dieu kien su dung-->
                        <br class="clean" />
                        <!--introduction product-->
                        <div class="product_detail_Co">
                           <p style="text-align: justify;">
                            	Cảm xúc v&ecirc;̀ thời trang dành cho phái đẹp dường như lu&ocirc;n b&acirc;́t t&acirc;̣n qua đ&ocirc;i bàn tay đ&acirc;̀y ngh&ecirc;̣ thu&acirc;̣t của các nhà thi&ecirc;́t k&ecirc;́. Chính vì lẽ đó mà th&ecirc;́ giới thời trang lu&ocirc;n đa sắc màu, đa chủng loại với r&acirc;́t nhi&ecirc;̀u ki&ecirc;̉u dáng khác nhau cho &ldquo;m&ocirc;̣t nửa th&ecirc;́ giới&rdquo; thỏa sức lựa chọn phong cách ri&ecirc;ng phù hợp với mình. Nhận thức được nhu cầu đ&oacute;, <strong>Shop Amme</strong> lu&ocirc;n đưa ra nhiều mẫu m&atilde; phong ph&uacute;, để đ&aacute;p ứng nhu cầu ng&agrave;y c&agrave;ng cao của mọi kh&aacute;ch h&agrave;ng.</p>
                            <p style="text-align: justify;">
                            	&nbsp;</p>
                              <p style="text-align: justify;">
                            	Cảm xúc v&ecirc;̀ thời trang dành cho phái đẹp dường như lu&ocirc;n b&acirc;́t t&acirc;̣n qua đ&ocirc;i bàn tay đ&acirc;̀y ngh&ecirc;̣ thu&acirc;̣t của các nhà thi&ecirc;́t k&ecirc;́. Chính vì lẽ đó mà th&ecirc;́ giới thời trang lu&ocirc;n đa sắc màu, đa chủng loại với r&acirc;́t nhi&ecirc;̀u ki&ecirc;̉u dáng khác nhau cho &ldquo;m&ocirc;̣t nửa th&ecirc;́ giới&rdquo; thỏa sức lựa chọn phong cách ri&ecirc;ng phù hợp với mình. Nhận thức được nhu cầu đ&oacute;, <strong>Shop Amme</strong> lu&ocirc;n đưa ra nhiều mẫu m&atilde; phong ph&uacute;, để đ&aacute;p ứng nhu cầu ng&agrave;y c&agrave;ng cao của mọi kh&aacute;ch h&agrave;ng.</p>
                             <p style="text-align: justify;">
                            	Cảm xúc v&ecirc;̀ thời trang dành cho phái đẹp dường như lu&ocirc;n b&acirc;́t t&acirc;̣n qua đ&ocirc;i bàn tay đ&acirc;̀y ngh&ecirc;̣ thu&acirc;̣t của các nhà thi&ecirc;́t k&ecirc;́. Chính vì lẽ đó mà th&ecirc;́ giới thời trang lu&ocirc;n đa sắc màu, đa chủng loại với r&acirc;́t nhi&ecirc;̀u ki&ecirc;̉u dáng khác nhau cho &ldquo;m&ocirc;̣t nửa th&ecirc;́ giới&rdquo; thỏa sức lựa chọn phong cách ri&ecirc;ng phù hợp với mình. Nhận thức được nhu cầu đ&oacute;, <strong>Shop Amme</strong> lu&ocirc;n đưa ra nhiều mẫu m&atilde; phong ph&uacute;, để đ&aacute;p ứng nhu cầu ng&agrave;y c&agrave;ng cao của mọi kh&aacute;ch h&agrave;ng.</p>
                             <p style="text-align: justify;">
                            	Cảm xúc v&ecirc;̀ thời trang dành cho phái đẹp dường như lu&ocirc;n b&acirc;́t t&acirc;̣n qua đ&ocirc;i bàn tay đ&acirc;̀y ngh&ecirc;̣ thu&acirc;̣t của các nhà thi&ecirc;́t k&ecirc;́. Chính vì lẽ đó mà th&ecirc;́ giới thời trang lu&ocirc;n đa sắc màu, đa chủng loại với r&acirc;́t nhi&ecirc;̀u ki&ecirc;̉u dáng khác nhau cho &ldquo;m&ocirc;̣t nửa th&ecirc;́ giới&rdquo; thỏa sức lựa chọn phong cách ri&ecirc;ng phù hợp với mình. Nhận thức được nhu cầu đ&oacute;, <strong>Shop Amme</strong> lu&ocirc;n đưa ra nhiều mẫu m&atilde; phong ph&uacute;, để đ&aacute;p ứng nhu cầu ng&agrave;y c&agrave;ng cao của mọi kh&aacute;ch h&agrave;ng.</p>
                             <p style="text-align: justify;">
                            	Cảm xúc v&ecirc;̀ thời trang dành cho phái đẹp dường như lu&ocirc;n b&acirc;́t t&acirc;̣n qua đ&ocirc;i bàn tay đ&acirc;̀y ngh&ecirc;̣ thu&acirc;̣t của các nhà thi&ecirc;́t k&ecirc;́. Chính vì lẽ đó mà th&ecirc;́ giới thời trang lu&ocirc;n đa sắc màu, đa chủng loại với r&acirc;́t nhi&ecirc;̀u ki&ecirc;̉u dáng khác nhau cho &ldquo;m&ocirc;̣t nửa th&ecirc;́ giới&rdquo; thỏa sức lựa chọn phong cách ri&ecirc;ng phù hợp với mình. Nhận thức được nhu cầu đ&oacute;, <strong>Shop Amme</strong> lu&ocirc;n đưa ra nhiều mẫu m&atilde; phong ph&uacute;, để đ&aacute;p ứng nhu cầu ng&agrave;y c&agrave;ng cao của mọi kh&aacute;ch h&agrave;ng.</p>
                             <p style="text-align: justify;">
                            	Cảm xúc v&ecirc;̀ thời trang dành cho phái đẹp dường như lu&ocirc;n b&acirc;́t t&acirc;̣n qua đ&ocirc;i bàn tay đ&acirc;̀y ngh&ecirc;̣ thu&acirc;̣t của các nhà thi&ecirc;́t k&ecirc;́. Chính vì lẽ đó mà th&ecirc;́ giới thời trang lu&ocirc;n đa sắc màu, đa chủng loại với r&acirc;́t nhi&ecirc;̀u ki&ecirc;̉u dáng khác nhau cho &ldquo;m&ocirc;̣t nửa th&ecirc;́ giới&rdquo; thỏa sức lựa chọn phong cách ri&ecirc;ng phù hợp với mình. Nhận thức được nhu cầu đ&oacute;, <strong>Shop Amme</strong> lu&ocirc;n đưa ra nhiều mẫu m&atilde; phong ph&uacute;, để đ&aacute;p ứng nhu cầu ng&agrave;y c&agrave;ng cao của mọi kh&aacute;ch h&agrave;ng.</p>
                             <p style="text-align: justify;">
                            	Cảm xúc v&ecirc;̀ thời trang dành cho phái đẹp dường như lu&ocirc;n b&acirc;́t t&acirc;̣n qua đ&ocirc;i bàn tay đ&acirc;̀y ngh&ecirc;̣ thu&acirc;̣t của các nhà thi&ecirc;́t k&ecirc;́. Chính vì lẽ đó mà th&ecirc;́ giới thời trang lu&ocirc;n đa sắc màu, đa chủng loại với r&acirc;́t nhi&ecirc;̀u ki&ecirc;̉u dáng khác nhau cho &ldquo;m&ocirc;̣t nửa th&ecirc;́ giới&rdquo; thỏa sức lựa chọn phong cách ri&ecirc;ng phù hợp với mình. Nhận thức được nhu cầu đ&oacute;, <strong>Shop Amme</strong> lu&ocirc;n đưa ra nhiều mẫu m&atilde; phong ph&uacute;, để đ&aacute;p ứng nhu cầu ng&agrave;y c&agrave;ng cao của mọi kh&aacute;ch h&agrave;ng.</p>
                             <p style="text-align: justify;">
                            	Cảm xúc v&ecirc;̀ thời trang dành cho phái đẹp dường như lu&ocirc;n b&acirc;́t t&acirc;̣n qua đ&ocirc;i bàn tay đ&acirc;̀y ngh&ecirc;̣ thu&acirc;̣t của các nhà thi&ecirc;́t k&ecirc;́. Chính vì lẽ đó mà th&ecirc;́ giới thời trang lu&ocirc;n đa sắc màu, đa chủng loại với r&acirc;́t nhi&ecirc;̀u ki&ecirc;̉u dáng khác nhau cho &ldquo;m&ocirc;̣t nửa th&ecirc;́ giới&rdquo; thỏa sức lựa chọn phong cách ri&ecirc;ng phù hợp với mình. Nhận thức được nhu cầu đ&oacute;, <strong>Shop Amme</strong> lu&ocirc;n đưa ra nhiều mẫu m&atilde; phong ph&uacute;, để đ&aacute;p ứng nhu cầu ng&agrave;y c&agrave;ng cao của mọi kh&aacute;ch h&agrave;ng.</p>
                             <p style="text-align: justify;">
                            	Cảm xúc v&ecirc;̀ thời trang dành cho phái đẹp dường như lu&ocirc;n b&acirc;́t t&acirc;̣n qua đ&ocirc;i bàn tay đ&acirc;̀y ngh&ecirc;̣ thu&acirc;̣t của các nhà thi&ecirc;́t k&ecirc;́. Chính vì lẽ đó mà th&ecirc;́ giới thời trang lu&ocirc;n đa sắc màu, đa chủng loại với r&acirc;́t nhi&ecirc;̀u ki&ecirc;̉u dáng khác nhau cho &ldquo;m&ocirc;̣t nửa th&ecirc;́ giới&rdquo; thỏa sức lựa chọn phong cách ri&ecirc;ng phù hợp với mình. Nhận thức được nhu cầu đ&oacute;, <strong>Shop Amme</strong> lu&ocirc;n đưa ra nhiều mẫu m&atilde; phong ph&uacute;, để đ&aacute;p ứng nhu cầu ng&agrave;y c&agrave;ng cao của mọi kh&aacute;ch h&agrave;ng.</p>
                            
                            <p style="text-align: justify;">
                            	Tọa lạc tại địa chỉ 313 Huỳnh Văn B&aacute;nh, P.11, Q.Ph&uacute; Nhuận, Tp.HCM, <strong>Shop Amme</strong>&nbsp;n&ocirc;̉i b&acirc;̣t bởi đ&acirc;y l&agrave; địa chỉ chuy&ecirc;n kinh doanh c&aacute;c mặt h&agrave;ng thời trang hiện đại, với mẫu m&atilde;, chất liệu, k&iacute;ch cỡ đa dạng. Với gu thẩm mỹ cao v&agrave; nguồn h&agrave;ng phong ph&uacute;, chất lượng.</p>
                        </div>
                        <!--End introduction product-->
                </div>
            <!--End Product detail left-->
                <!--Product detail right-->
                <div class="detail_R">
                    
                    <div class="time">
                        Facebook Share (Anh Nguyên làm lại cái này giúp em với nhé)
                    </div>
                    <div class="time">
                        <p>Thời hạn chấp nhận thẻ:</p>
                        <p class="time_1">Từ 27/02/2012 đến 27/03/2012</p>
                    </div>
                    <div class="address_border">
                        <div class="address">
                            <h3>
                                Địa chỉ:
                            </h3>
                            <p>
                                313 Huỳnh Văn B&#225;nh, Phường 11, Quận Ph&#250; Nhuận, Hồ Ch&#237; Minh</p>
                            <p>
                                ĐT: 0938 960 079</p>
                            <span>
                                <a onclick="ShowMap('/Uploads/Branches/506/439_506_photo.jpg','313 Huỳnh Văn B&#225;nh, Phường 11' + ', Quận Ph&#250; Nhuận' + ', Hồ Ch&#237; Minh')" href="javascript:void(0);"><b><img align="absmiddle" src="Content/images/map.png"/>Bản Đồ</b></a></span>
                            <p class="line1">
                                &nbsp;</p>
                        </div>
                    </div>
                    
                    <div class="title_page">
                        <div class="title_page_L"></div>
                        <div class="title_page_Ce">Địa điểm tương tự</div>
                        <div class="title_page_R">
                        </div>
                    </div>
                    <br class="clean" />
                    <div id="other_product">
                        <article class="normal-post entry">
                        	<div class="main_content">
         							<div class="thumb">
                        				<a href="/preview/Notebook/2011/11/27/the-haunted-woods/">
                        					<img src="images/simple/2.jpg" width="279" height="180" class='n-post-image'  alt='The Haunted Woods' />					<span class="overlay"></span>
                        				</a>
                                        <span class="name"><span class="sale">Giảm giá: </span>30%</span>
                        			</div> 	<!-- end .thumb -->
                        				
                        		<div class="content">
                        			<!--h2 class="title"><a href="/preview/Notebook/2011/11/27/the-haunted-woods/">The Haunted Woods</a></h2-->
                        			
                        				<!--p class="meta">
                        		 By <a href="/preview/Notebook/author/admin/" title="Posts by admin" rel="author">admin</a> on 11-27-2011	</p-->
                        			
                        			<p>Difference Coffee - Sang trọng quyến rũ trong không gian 3D tuyệt vời...</p>
                        		</div> <!-- end .content-->
                        	</div> <!-- end .main_content-->
                        		
                        	<div class="center_layer"></div>
                        	<div class="bottom_layer"></div>
                        </article>
                        
                        <article class="video entry">
            				<div class="img">
                    			<a href="http://www.youtube.com/watch?v=MKfDwChOoHI" class="et_video_lightbox" title="Priscilla Ahn Dream">
                    				<span class="video_box">
                    					<img src="images/simple/2.jpg" width="279" height="180" class='video-image'  alt='Priscilla Ahn Dream' />				</span>
                    				<span class="overlay"></span>
                    				<span class="play"></span>
                    			</a>
                                <span class="name_1"><span class="sale">Giảm giá: </span>30%</span>
                    		</div> 	<!-- end .img -->
                    		
                        	<div class="content">
                        		<p>Difference Coffee - Sang trọng quyến rũ trong không gian 3D tuyệt vời...</p>
                        	</div>
                        </article>
                        <article class="normal-post entry">
                        	<div class="main_content">
         							<div class="thumb">
                        				<a href="/preview/Notebook/2011/11/27/the-haunted-woods/">
                        					<img src="images/simple/2.jpg" width="279" height="180" class='n-post-image'  alt='The Haunted Woods' />					<span class="overlay"></span>
                        				</a>
                                        <span class="name"><span class="sale">Giảm giá: </span>30%</span>
                        			</div> 	<!-- end .thumb -->
                        				
                        		<div class="content">
                        			<!--h2 class="title"><a href="/preview/Notebook/2011/11/27/the-haunted-woods/">The Haunted Woods</a></h2-->
                        			
                        				<!--p class="meta">
                        		 By <a href="/preview/Notebook/author/admin/" title="Posts by admin" rel="author">admin</a> on 11-27-2011	</p-->
                        			
                        			<p>Difference Coffee - Sang trọng quyến rũ trong không gian 3D tuyệt vời...</p>
                        		</div> <!-- end .content-->
                        	</div> <!-- end .main_content-->
                        		
                        	<div class="center_layer"></div>
                        	<div class="bottom_layer"></div>
                        </article>
                        
                        <article class="video entry">
            				<div class="img">
                    			<a href="http://www.youtube.com/watch?v=MKfDwChOoHI" class="et_video_lightbox" title="Priscilla Ahn Dream">
                    				<span class="video_box">
                    					<img src="images/simple/2.jpg" width="279" height="180" class='video-image'  alt='Priscilla Ahn Dream' />				</span>
                    				<span class="overlay"></span>
                    				<span class="play"></span>
                    			</a>
                                <span class="name_1"><span class="sale">Giảm giá: </span>30%</span>
                    		</div> 	<!-- end .img -->
                    		
                        	<div class="content">
                        		<p>Difference Coffee - Sang trọng quyến rũ trong không gian 3D tuyệt vời...</p>
                        	</div>
                        </article>
                    </div>
                    <br class="clean" />
                </div>
                <!--End Product detail right-->
            </div>
        </div>
        <div class="index_border_B"></div>
    </div>
    <!--End main content-->