<div id="warrap_product">
    <div id="content_secsion">
        <!-- Content -->
    	<section class="padcontent2">
    		<div class="container_12">
    			<div class="wrapper">
    				<div class="grid_8">
                        <?php echo $this->Showpath($this);	?>
                        <div class="clear"></div>
    					<div class="wrapper indent">
                            <div id="produc_indent">
                            
                                <?php 
                                $this->showProducts($this,array('local'=>'main'));
                                ?>
        						
                                <div class="clear"></div>
                                <div class="pagination">                                
                                <?php 
                                $currentUrl = $this->baseUrl('san-pham');
                                echo $this->paginationControl($this->panigator,'Sliding','pagination_product.phtml',array('currentUrl'=>$currentUrl));
                                ?>                                
                            	</div>
                                <div class="clear"></div>
                            </div>
    					</div>
    				</div>
    				<div class="grid_4">
    					<!--h4>Featured Services</h4-->
    					<?php 
                        $this->showProducts($this,array('local'=>'category'));
                        ?>
    					<div class="padline3"><div class="lineH"></div></div>
                        <?php 
                        $this->showProducts($this,array('local'=>'new_product'));
                        ?>
                        
                        <!--Quang cao-->
                        <?php $this->ShowADSByModuleAndPosition('right',$this->arrParam['module'],$this,null);?>
    				</div>
    			</div>
    		</div>
    	</section>
    </div>
</div>