<?php

?>

<div id="warrap_product">
    <div id="content_secsion">
        <!-- Content -->
    	<section class="padcontent2">
    		<div class="container_12">
    			<div class="wrapper">
    				<div class="grid_8">
                        <?php echo $this->Showpath($this);	?>
                        <div class="clear"></div>
    					<div class="wrapper indent">
                            <div id="produc_indent">
                                
                                <?php echo $this->showProducts($this,array('local'=>'block_main'));	?>
                                <div class="clear"></div>
                            </div>
    					</div>
    				</div>
    				<div class="grid_4">
    					<!--h4>Featured Services</h4-->
    					<?php 
                        $this->showProducts($this,array('local'=>'category'));
                        ?>
    					<div class="padline3"><div class="lineH"></div></div>
                        <?php 
                        $this->showProducts($this,array('local'=>'new_product'));
                        ?>
                        
                        <!--Quang cao-->
                        <?php $this->ShowADSByModuleAndPosition('right',$this->arrParam['module'],$this);?>
    				</div>
    			</div>
    		</div>
    	</section>
    </div>
</div>