


<div class="main-container col2-right-layout">

    <?php
/*
foreach ($this->listProducts as $key => $value) {
  $this->showProducts($this,array('local'=>'block_item','info'=>$value));
}*/
/*
$cacheManager=Zend_Registry::get('cacheManager',$cache);
$cacheManager=$cacheManager['productindexlist'];
$cache = Zend_Cache::factory($cacheManager['frontend']['name'],
                             $cacheManager['backend']['name'],
                             $cacheManager['frontend']['options'],
                             $cacheManager['backend']['options']);



    [cat_name] => vong-tay
    [cat_id] => 275
    [page] => 2
    [module] => product
    [controller] => index
    [action] => list
    [ssFilter] => Array
        (
            [cat_id] => 
        )

    [paginator] => Array
        (
            [itemCountPerPage] => 9
            [pageRange] => 3
            [currentPage] => 2
        )
*/

if(isset($this->arrParam['page']))
    $cpage=$this->arrParam['page'];
else
    $cpage=1;
$cache=Zendvn_Cache::getCacheObject('productindexlist');
$keyCache='view_cachedatalistbycategory_'.$this->arrParam['cat_id'].'_'.$cpage;
if (!($cache->start($keyCache))) {
 
?>
<?php 
    $currentUrl = $this->baseUrl($this->currentController . '/index');
    $htmlPaging=$this->paginationControl($this->panigator,'Sliding','pagination_product.phtml',array('currentUrl'=>$currentUrl,'objView'=>$this));
?>
            <div class="main">
               
                <div class="col-main">
				
									<div class="wrapper_col-inner">
						 <div class="breadcrumbs">
    <ul>
                    <li class="home">
                            <a href="<?php echo DOMAIN_NAME;?>" title="Go to Home Page">Trang chủ</a>
                                        <span> &nbsp; </span>
                        </li>
                    <li class="category53">
                            <strong><?php echo $this->categoryDetail['name'];?></strong>
                                    </li>
            </ul>
</div>
                    	                    	<div class="page-title category-title">
        <h1><?php echo $this->categoryDetail['name'];?></h1>
</div>




    <div class="category-products">
    <div class="toolbar">
    <div class="pager">
    	<?php echo $htmlPaging;?>
    </div>
    
    

    </div>

        
    </div>
	<div class="products-container">
		<div class="products-container-inner">
<?php
	

			$numProduct=count($this->listProducts);
			$i=0;
			$listProducts=$this->listProducts;
			while ($i <= $numProduct) {
				echo '<ul class="products-grid">';
				if($listProducts[$i]!=null)
                {
					echo '<li class="item first">';
	                $this->showProducts($this,array('local'=>'block_item','info'=>$listProducts[$i]));
                	echo '</li>';
                }
                if($listProducts[$i+1]!=null)
                {
                    
                    echo '<li class="item">';
                    $this->showProducts($this,array('local'=>'block_item','info'=>$listProducts[$i+1]));
                    echo '</li>';    
                }
				if($listProducts[$i+2]!=null)
                {
                    
    				echo '<li class="item last">';
                    $this->showProducts($this,array('local'=>'block_item','info'=>$listProducts[$i+2]));
                    echo '</li>';
                }
				echo '</ul>';

				$i+=3;
			}

			
		?>  
    
		        		        		        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
		    		</div>
	</div>
    <div class="toolbar-bottom">
        <div class="toolbar">
    <div class="pager">        
        <?php echo $htmlPaging;?>
    </div>
    
    

    </div>

       
    </div>
    </div>
</div>
					</div>

<?php
 
    $cache->end(); // output buffering ends
 
}
 
?>
					<div class="col-inner_bottom"></div>
                </div>
                <div class="col-right sidebar">

				    <?php $this->showWidget($this,array('widget'=>'minisearch'));?>
				    <?php $this->showWidget($this,array('widget'=>'fanpage'));?>
				    <?php $this->showWidget($this,array('widget'=>'contact'));?>
                    <?php $this->showWidget($this,array('widget'=>'music'));?>
				</div>
            </div>
        </div>