 <?php

 $arrayHot=array();
 $arrayNormal=array();
 foreach($this->listProductByCat as $key=>$info)
 {
    if($info['is_hot']=='1')
    {
        $arrayHot[]=$info;
        
    }  
    else
    {
        $arrayNormal[]=$info;
        
    }
    
 }
 ?>
 
 <!--Main conent-->
    <div id="baseDiv">
       
        <!--div class="index_border_T"></div-->
        <!--search-->
        <?php $this->showSearch($this);?>
        <!--end search-->
        <div class="index_border_M">
           
	       <?php 
          if(count($arrayHot))
          {
          ?>
		   <!--List Product category-->
            <div class="category_product">
                <div class="title_page">
                    <div class="title_page_L"></div>
                    <div class="title_page_Ce">Có <?php echo count($arrayHot);?> địa điểm chấp nhận thẻ mua sắm khuyên dùng</div>
                    <div class="title_page_R"></div>
                </div>
				
				
				<?php				
                
				$this->showProducts($this,array('local'=>'block1','listPro'=>$arrayHot));
				?>
            </div>
            <!--End List Product category-->
            <br class="clean" />
			<?php
            }
            ?>
			<!--List Product category-->
            <div class="category_product">
                <div class="title_page">
                    <div class="title_page_L"></div>
                    <div class="title_page_Ce">Có <?php echo count($arrayNormal);?> địa điểm chấp nhận thẻ mua sắm</div>
                    <div class="title_page_R"></div>
                </div>
				
				
				<?php				
                
				$this->showProducts($this,array('local'=>'block1','listPro'=>$arrayNormal));
				?>
            </div>
            <!--End List Product category-->
            <br class="clean" />
			
        </div>
        
    </div>
    <!--End main content-->