<?php 
	$name_field = $this->formText('f_name',$this->Item['name'],array('class'=>'txtmedium'));
    $module_field = $this->formText('f_module',$this->Item['module'],array('class'=>'txtmedium'));
    $controller_field = $this->formText('f_controller',$this->Item['controller'],array('class'=>'txtmedium'));
    $action_field = $this->formText('f_action',$this->Item['action'],array('class'=>'txtmedium'));
	
?>
<form name="appForm" method="post" action="">

                        <?php echo $this->render('admin-privileges/toolbar/index.php')?>
                        <div class="clr"></div>
                        <?php echo $this->render('admin-privileges/sublink/index.php')?>
                        
                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
						<div id="adminfieldset">
                             <div class="adminheader">Detail</div>
								
								<div id="row">
                                    <div class="label">Name:</div>
                                    <?php echo $name_field;?>			
                                </div>
                                <div class="clr"></div>
                                <div id="row">
                                    <div class="label">Module:</div>
                                    <?php echo $module_field;?>			
                                </div>
                                <div class="clr"></div>
                                <div id="row">
                                    <div class="label">Controller:</div>
                                    <?php echo $controller_field;?>			
                                </div>
                                <div class="clr"></div>
                                <div id="row">
                                    <div class="label">Action:</div>
                                    <?php echo $action_field;?>			
                                </div>
                                <div class="clr"></div>
                                
                                
                                
							</div>
							
                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>