<?php 
	
	$ssFilter = $this->arrParam['ssFilter'];
	
	//CREATE SEARCH AREA
	$keywords = $this->formText('keywords',$ssFilter['keywords'],array('class'=>'txtshort'));
	$linkSearch = $this->baseUrl($this->currentController . '/filter/type/search/key/1');
	$btnSearch = $this->formButton('search-now','Search now',
									array('onclick'=>"OnSubmitForm('" . $linkSearch . "')"));
	$linkResetSearch = $this->baseUrl($this->currentController . '/filter/type/search/key/0');							
	$btnResetSearch = $this->formButton('clear-keywords','Clear',
									array('onclick'=>"OnSubmitForm('" . $linkResetSearch . "')"));	
	 $strSearch = $keywords . ' ' . $btnSearch . ' ' . $btnResetSearch;
     
     
     
     $action_link 	= $this->baseUrl($this->currentController . '/filter/type/order');
     $lblId 	= $this->cmsLinkSort('ID','g.id',$ssFilter,
										$this->imgUrl . '/icon',$action_link);
	$lblName 	= $this->cmsLinkSort('Name','g.name',$ssFilter,
										$this->imgUrl . '/icon',$action_link);
    $lblModule 	= $this->cmsLinkSort('Module','g.module',$ssFilter,
										$this->imgUrl . '/icon',$action_link);
	
	$lblController		= $this->cmsLinkSort('Controller','g.controller',$ssFilter,
										$this->imgUrl . '/icon',$action_link);
										
	$lblAction		= $this->cmsLinkSort('Action','g.action',$ssFilter,
										$this->imgUrl . '/icon',$action_link);			

											
     																	
?>
<form name="appForm" method="post" action="">



                        <?php echo $this->render('admin-privileges/toolbar/index.php')?>
                        <div class="clr"></div>
                         <?php echo $this->render('admin-privileges/sublink/index.php')?>

                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
								<div id="filters">
									<div>
										<?php echo $strSearch;?>
									</div>
								</div>	

                                <!-- Area 4: In du lieu lay tu database -->
                                <table class="adminlist">
                                    <thead>
                                        <tr>
                                            <th width="43" >
                                            	<input type="checkbox" name="checkbox" id="checkbox" onclick="checkedAll()">
                                           	</th>
                                            <th><?php echo $lblName;?></th>
                                            <th width="150"><?php echo $lblModule;?></th>
                                            <th width="150"><?php echo $lblController;?></th>
                                            <th width="150"><?php echo $lblAction;?></th>                                            						
                                            <th width="90">Control</th>

                                            <th width="34"><?php echo $lblId;?></th>
                                        </tr>
                                    </thead>
									<?php 
										foreach($this->Items as $key => $val){
											$id 			= $val['id'];
											$name 	        = $val['name'];
											$module		    = $val['module'];
                                            $controller		= $val['controller'];
                                            $action		    = $val['action'];
											
											$linkInfo		= $this->baseUrl($this->currentController . '/info/id/' . $id);											
											$btnInfo		= $this->cmsIconButton('View Item',$this->imgUrl . '/icon_info.png',$linkInfo);
											
											$linkEdit		= $this->baseUrl($this->currentController . '/edit/id/' . $id);
											$btnEdit		= $this->cmsIconButton('Edit Item',$this->imgUrl . '/icon_edit.png',$linkEdit);
											
											$linkDelete		= $this->baseUrl($this->currentController . '/delete/id/' . $id);
											$btnDelete		= $this->cmsIconButton('Delete Item',$this->imgUrl . '/icon_del.png',$linkDelete);
										
											$strIconButton	= $btnInfo . ' ' . $btnEdit . ' ' . $btnDelete;
											
											$cid			= $this->formCheckbox('cid[]',$val['id']);
									?>
                                    <tr class="even">						
                                        <td align="center"><?php echo $cid;?></td>
                                        <td align="left"><?php echo $name;?></td>
                                        <td align="center"><?php echo $module;?></td>
                                        <td align="center"><?php echo $controller;?></td>
                                        <td align="center"><?php echo $action;?></td>
                                        <td align="center"><?php echo $strIconButton;?></td>
                                        <td align="center"><?php echo $id;?></td>
                                    </tr>
                                    <?php 
										}
                                    ?>
                                    <!-- BEGIN: PAGINATION (FOOT) -->
                                    <tfoot>
                                        <tr>
                                            <td colspan="9">
                                                <div class="container">
                                                    <div class="pagination">
                                                        <?php 
                                                        				
                                                        	$currentUrl = $this->baseUrl($this->currentController . '/index');
                                                        	echo $this->paginationControl($this->panigator,'Sliding','pagination.phtml',array('currentUrl'=>$currentUrl));
                                                        	// display items per page
                                                        	$linkSlbPagging = $this->baseUrl($this->currentController . '/filter/type/pagging');
                                                        	$options = array(5=>'5',
                                                        					10=>'10',
                                                        					20=>'20',
                                                        					30=>'30',
                                                        					50=>'50',
                                                        					100=>'100',
                                                        					200=>'200');
                                                        	if($ssFilter['pagging']=='')
                                                        		$ssFilter['pagging']=20;
															$numPerPage = $this->formSelect('pagging',$ssFilter['pagging'],
																							array('onchange'=>"OnSubmitForm('" . $linkSlbPagging . "')"),
																							$options);
															echo 'Items per page:'.$numPerPage;
                                                        ?>
                                                        <div class="limit"></div>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>					
                                    </tfoot>				<!-- END: PAGINATION (FOOT) -->
                                </table>
                                <!-- Area 4: In du lieu lay tu database - End -->

                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>