
				<div id="element-box">

					
					<div class="t">
						<div class="t">
							<div class="t"></div>
						</div>
					</div>
					<div class="m" >
						<table class="adminform">
						<tr>
							<td width="55%" valign="top">

		<div id="cpanel">
			
			<!-- Nội dung chèn tại đây-->
		</div>
	
							</td>

		<td width="45%" valign="top">
			<div id="content-pane" class="pane-sliders">
				<!-- slide content -->
				<div class="panel">
					<h3 class="jpane-toggler title" id="cpanel-panel-custom">
						<span>Welcome to Royal CMS</span>
					</h3>
					<div class="jpane-slider content">
						<div style="padding: 5px"><p>Welcome</p></div>
					</div>
				</div>
				<!-- slide content end -->
				<!-- slide content -->
				<div class="panel">
					<h3 class="jpane-toggler title" id="cpanel-panel-logged">
						<span>Logged in Users</span>
					</h3>
					<div class="jpane-slider content">
	<table class="adminlist">
		<thead>
			<tr>
				<td class="title"><strong>#</strong></td>
				<td class="title"><strong>Name</strong></td>
				<td class="title"><strong>Group</strong></td>
				<td class="title"><strong>Client</strong></td>
				<td class="title"><strong>Last Activity</strong></td>
				<td class="title"><strong>Logout</strong></td>
			</tr>
		</thead>
		<tbody>

			<tr>
				<td width="5%">1</td>
				<td><a href="#" title="Edit User">admin</a></td>
				<td>Super Administrator</td>
				<td>administrator</td>
				<td>0.0 hours ago</td>
				<td></td>
			</tr>
		</tbody>
	</table>
</div></div>
<!-- slide content end -->
<!-- slide content -->
				<div class="panel">
					<h3 class="jpane-toggler title" id="cpanel-panel-logged">
						<span>Top 10 Last Register</span>
					</h3>
					<div class="jpane-slider content">
	<table class="adminlist">
		<thead>
			<tr>
				<td class="title"><strong>#</strong></td>
				<td class="title"><strong>User name</strong></td>
				<td class="title"><strong>Group</strong></td>
				<td class="title"><strong>Register</strong></td>
			</tr>
		</thead>
		<tbody>

			<tr>
				<td width="5%">1</td>
				<td><a href="#" title="Edit User">admin</a></td>
				<td>Super Administrator</td>
				<td>11/11/2011 11:11:11</td>
			</tr>
			<tr>
				<td width="5%">2</td>
				<td><a href="#" title="Edit User">hoanggia</a></td>
				<td>Administrator</td>
				<td>11/11/2011 11:11:11</td>
			</tr>
			<tr>
				<td width="5%">3</td>
				<td><a href="#" title="Edit User">vukhanh</a></td>
				<td>Moderator</td>
				<td>11/11/2011 11:11:11</td>
			</tr>
			<tr>
				<td width="5%">4</td>
				<td><a href="#" title="Edit User">hellsoul</a></td>
				<td>Register</td>
				<td>11/11/2011 11:11:11</td>
			</tr>
			<tr>
				<td width="5%">5</td>
				<td><a href="#" title="Edit User">hellsoul</a></td>
				<td>Register</td>
				<td>11/11/2011 11:11:11</td>
			</tr>
			<tr>
				<td width="5%">6</td>
				<td><a href="#" title="Edit User">admin</a></td>
				<td>Super Administrator</td>
				<td>11/11/2011 11:11:11</td>
			</tr>
			<tr>
				<td width="5%">7</td>
				<td><a href="#" title="Edit User">hoanggia</a></td>
				<td>Administrator</td>
				<td>11/11/2011 11:11:11</td>
			</tr>
			<tr>
				<td width="5%">8</td>
				<td><a href="#" title="Edit User">vukhanh</a></td>
				<td>Moderator</td>
				<td>11/11/2011 11:11:11</td>
			</tr>
			<tr>
				<td width="5%">9</td>
				<td><a href="#" title="Edit User">hellsoul</a></td>
				<td>Register</td>
				<td>11/11/2011 11:11:11</td>
			</tr>
			<tr>
				<td width="5%">10</td>
				<td><a href="#" title="Edit User">hellsoul</a></td>
				<td>Register</td>
				<td>11/11/2011 11:11:11</td>
			</tr>
		</tbody>
	</table>
</div></div>
<!-- slide content end -->
<!-- slide content -->
				<div class="panel">
					<h3 class="jpane-toggler title" id="cpanel-panel-logged">
						<span>Top 10 Last Arcticle</span>
					</h3>
					<div class="jpane-slider content">
	<table class="adminlist">
		<thead>
			<tr>
				<td class="title"><strong>#</strong></td>
				<td class="title"><strong>Title</strong></td>
				<td class="title"><strong>Category</strong></td>
				<td class="title"><strong>Created by</strong></td>
				<td class="title"><strong>Created</strong></td>
			</tr>
		</thead>
		<tbody>

			<tr>
				<td width="5%">1</td>
				<td><a href="#" title="Edit User">Thị trường ông Công, ông Táo sốt giá </a></td>
				<td>Thời sự</td>
				<td>hoanggia</td>
				<td>11/11/2011 11:11:11</td>
			</tr>
			<tr>
				<td width="5%">2</td>
				<td><a href="#" title="Edit User">Thị trường ông Công, ông Táo sốt giá </a></td>
				<td>Thời sự</td>
				<td>hoanggia</td>
				<td>11/11/2011 11:11:11</td>
			</tr>
			<tr>
				<td width="5%">3</td>
				<td><a href="#" title="Edit User">Thị trường ông Công, ông Táo sốt giá </a></td>
				<td>Thời sự</td>
				<td>hoanggia</td>
				<td>11/11/2011 11:11:11</td>
			</tr>
			<tr>
				<td width="5%">4</td>
				<td><a href="#" title="Edit User">Thị trường ông Công, ông Táo sốt giá </a></td>
				<td>Thời sự</td>
				<td>hoanggia</td>
				<td>11/11/2011 11:11:11</td>
			</tr>
			<tr>
				<td width="5%">5</td>
				<td><a href="#" title="Edit User">Thị trường ông Công, ông Táo sốt giá </a></td>
				<td>Thời sự</td>
				<td>hoanggia</td>
				<td>11/11/2011 11:11:11</td>
			</tr>
			<tr>
				<td width="5%">6</td>
				<td><a href="#" title="Edit User">Thị trường ông Công, ông Táo sốt giá </a></td>
				<td>SThời sự</td>
				<td>hoanggia</td>
				<td>11/11/2011 11:11:11</td>
			</tr>
			<tr>
				<td width="5%">7</td>
				<td><a href="#" title="Edit User">Thị trường ông Công, ông Táo sốt giá </a></td>
				<td>Thời sự</td>
				<td>hoanggia</td>
				<td>11/11/2011 11:11:11</td>
			</tr>
			<tr>
				<td width="5%">8</td>
				<td><a href="#" title="Edit User">Thị trường ông Công, ông Táo sốt giá </a></td>
				<td>Thời sự</td>
				<td>hoanggia</td>
				<td>11/11/2011 11:11:11</td>
			</tr>
			<tr>
				<td width="5%">9</td>
				<td><a href="#" title="Edit User">Thị trường ông Công, ông Táo sốt giá </a></td>
				<td>Thời sự</td>
				<td>hoanggia</td>
				<td>11/11/2011 11:11:11</td>
			</tr>
			<tr>
				<td width="5%">10</td>
				<td><a href="#" title="Edit User">Thị trường ông Công, ông Táo sốt giá </a></td>
				<td>Thời sự</td>
				<td>hoanggia</td>
				<td>11/11/2011 11:11:11</td>
			</tr>
		</tbody>
	</table>
</div></div>
<!-- slide content end -->
</div>
							</td>
						</tr>
						</table>

						<div class="clr"></div>
					</div>
					<div class="b">
						<div class="b">
							<div class="b"></div>
						</div>
					</div>
				</div>
				<noscript>
					Warning! JavaScript must be enabled for proper operation of the Administrator back-end.				</noscript>

				<div class="clr"></div>
	