<?php 

	
	$title 			= $this->formText('name',$this->Item['name'],array('class'=>'txtmedium'));
	
	$summary 		= $this->cmsEditor('summary',$this->cmsConvertDbToView($this->Item['summary']),$width = '100%',$height = 200);
	$summary1 		= $this->cmsEditor('summary_1',$this->cmsConvertDbToView($this->Item['summary_1']),$width = '100%',$height = 500);
	$summary2 		= $this->cmsEditor('summary_2',$this->cmsConvertDbToView($this->Item['summary_2']),$width = '100%',$height = 500);
    $summary3 		= $this->cmsEditor('summary_3',$this->cmsConvertDbToView($this->Item['summary_3']),$width = '100%',$height = 500);
	$summary4 		= $this->cmsEditor('summary_4',$this->cmsConvertDbToView($this->Item['summary_4']),$width = '100%',$height = 500);
    $summary5 		= $this->cmsEditor('summary_5',$this->cmsConvertDbToView($this->Item['summary_5']),$width = '100%',$height = 500);
    $address 		= $this->cmsEditor('address',$this->cmsConvertDbToView($this->Item['address']),$width = '100%',$height = 200,'basic');
	$contact		= $this->cmsEditor('contact',$this->cmsConvertDbToView($this->Item['contact']),$width = '100%',$height = 200,'basic');
	
    $map_x 			= $this->formText('map_x',$this->Item['map_x'],array('class'=>'txtmedium'));
    $map_y 			= $this->formText('map_y',$this->Item['map_y'],array('class'=>'txtmedium'));
    
	$description	= $this->cmsEditor('description',$this->cmsConvertDbToView($this->Item['description']),$width = '100%',$height = 500);
	
	$image			= $this->formFile('image',array('style'=>'width: 250px'));
	$image_current	= $this->formHidden('image_current',$this->Item['image']);
	$product_image	= '<img src="'.PUBLIC_URL.'/files/products/image/'.$this->Item['image'].'">';
	
	$image1			= $this->formFile('image1[]',array('style'=>'width: 250px'));
	$image1_current	= $this->formHidden('image1_current[]',$this->Item['image1[]']);
	$product_image1	= '<img src="'.PUBLIC_URL.'/files/products/image1/'.$this->Item['image1[]'].'">';	
	
	$map_image			= $this->formFile('map_image',array('style'=>'width: 250px'));
	$map_image_current	= $this->formHidden('map_image_current',$this->Item['map_image']);	
	$product_map_image	= '<img src="'.PUBLIC_URL.'/files/products/map/'.$this->Item['map_image'].'">';
	
	$price 			= $this->formText('price',$this->Item['price'],array('class'=>'txtmedium'));
	//$price_1		= $this->formText('price_1',$this->Item['price_1'],array('class'=>'txtmedium'));
    $percent		= $this->formText('percent',$this->Item['percent'],array('class'=>'txtmedium'));
    
	$options 		= array('No','Yes');
	$hot 			= $this->formRadio('hot',$this->Item['hot'],null,$options, ' ');
	
	$options 		= array('No','Yes');
	$status 		= $this->formRadio('status',$this->Item['status'],null,$options, ' ');
    
    $options 		= array('No','Yes');
	$is_top 		= $this->formRadio('is_top',$this->Item['is_top'],null,$options, ' ');
	
	$options 		= array('Enable','Disable');
	$comment 		= $this->formRadio('comment',$this->Item['comment'],null,$options, ' ');
	//danh sach category
	$options = $this->listCat;	
	$listCat = $this->cmsCategorySelect('cat_id',$this->Item['cat_id'],$options,array('style'=>'width:255px'));	
	//danh sach dia diem
    $options = $this->listLocation;	
	$listLocation = $this->cmsCategorySelect('district_id',$this->Item['district_id'],$options,array('style'=>'width:255px'));	
    
    
    
	$order			= $this->formText('order',$this->Item['order'],array('class'=>'txtmedium'));
	
	$start_day		= $this->cmsDatepicker('start_date',$this->Item['start_date'],array('class'=>'txtshort'), $this);
	$end_day		= $this->cmsDatepicker('end_date',$this->Item['end_date'],array('class'=>'txtshort'), $this);
	
    $start_day_isfront	= $this->cmsDatepicker('start_date_isfront',$this->Item['start_date_isfront'],array('class'=>'txtshort'), $this);
	$end_day_isfront	= $this->cmsDatepicker('end_date_isfront',$this->Item['end_date_isfront'],array('class'=>'txtshort'), $this);
	
    $start_day_ishot	= $this->cmsDatepicker('start_date_ishot',$this->Item['start_date_ishot'],array('class'=>'txtshort'), $this);
	$end_day_ishot		= $this->cmsDatepicker('end_date_ishot',$this->Item['end_date_ishot'],array('class'=>'txtshort'), $this);
	
    $start_day_isbusiness	= $this->cmsDatepicker('start_date_isbusiness',$this->Item['start_date_isbusiness'],array('class'=>'txtshort'), $this);
	$end_day_isbusiness		= $this->cmsDatepicker('end_date_isbusiness',$this->Item['end_date_isbusiness'],array('class'=>'txtshort'), $this);
	
    $start_day_istop	= $this->cmsDatepicker('start_date_istop',$this->Item['start_date_istop'],array('class'=>'txtshort'), $this);
	$end_day_istop		= $this->cmsDatepicker('end_date_istop',$this->Item['end_date_istop'],array('class'=>'txtshort'), $this);
	
    
    $options 		= array('No','Yes');
	$isbusiness 	= $this->formRadio('isbusiness',$this->Item['isbusiness'],null,$options, ' ');
	
    
	//------------------- PRINT ERRORS ------------------------
	if(!empty($this->errors)){
		$errors = $this->formErrors($this->errors );
	}
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">


                        <?php echo $this->render('admin-product/toolbar/index.php')?>
                        <div class="clr"></div>
                         <?php echo $this->render('admin-product/sublink/index.php')?>

                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
						<div id="adminfieldset">
                             <div class="adminheader">Detail</div>
										
                         		<?php 
                         		if(!empty($this->errors)){
                         			if($this->errors[0]=="success"){
                         				echo '<div id="success">';
										echo '<pre>';
											print_r($errors);
										echo '</pre>';
										echo '</div>';
                         				
                         			}
                         			else{
	                         			echo '<div id="errors">';
										echo '<pre>';
											print_r($errors);
										echo '</pre>';
										echo '</div>';
                         			}
								}
                         		
								?>
								
								<div id="row">
                                    <div class="label">Tiêu đề sản phẩm:</div>
                                    <?php echo $title;?>			
                                </div>
                                <div class="clr"></div>
                                
                                <div id="row">
                                    <div class="label">Ảnh sản phẩm nhỏ:</div>
                                    <?php echo $image.$image_current.'<br />'.$product_image;?>			
                                </div>
                                <div class="clr"></div>
                                
                                <div class="block_image1">
                                    <div id="row">
                                        <div class="label">Ảnh sản phẩm lớn:</div>
                                        <?php echo $image1.$image1_current.'<br />'.$product_image1;?>                                    			
                                    </div>
                                </div>
                                
                                <div id="row">
                                    <div class="label"></div>
                                <a href="javascript:void(0);" id="addMoreSlideImage"> <b>+</b> Thêm ảnh lớn</a>                                    			
                                </div>
                                <div id="row">
                                    
                                <?php echo $listPhoto;?>                                    			
                                </div>
                                
                                <div class="clr"></div>
                                
                                <div id="row">
                                    <div class="label">Giá:</div>
                                    <?php echo $price;?>			
                                </div>
                                <div class="clr"></div>
                                                                
                                 <div id="row">
                                    <div class="label">Hiện:</div>
                                    <?php echo $status;?>
                                </div>
                                <div class="clr"></div>
                                <div id="row">
                                    <div class="label">Sản phẩm đặc biệt:</div>
                                    <?php echo $hot;?>
                                </div>
                                <div class="clr"></div>
                                
                                
                                <div id="row">
                                    <div class="label">Category:</div>
                                    <?php echo $listCat;?>			
                                </div>
                                <div class="clr"></div>
                                
                                <div id="row">
                                    <div class="label">Order:</div>
                                    <?php echo $order;?>			
                                </div>
                                <div class="clr"></div>
                                
                                                                                                                 
                                <div id="row">
                                    <div class="label">Tóm tắt sản phẩm:</div>
                                    <div class="clr"></div>
                                    <?php echo $summary;?>	                                    		
                                </div>
                                
                                <div class="clr"></div>                                
                                <div id="row">
                                    <div class="label">Description:</div>
                                    <div class="clr"></div>
                                    <?php echo $description;?>			
                                </div>
                                <div class="clr"></div>
                                
                                
							</div>
							
                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>
<script>
$(document).ready(function(){
    var numFileBox=0;
    
        $("#addMoreSlideImage").unbind("click");
        $("#addMoreSlideImage").click(function(){
            
            var htmlContent=$($(this).parent().prev(".block_image1")).html();
            $(this).parent().before('<div class="block_image1">'+htmlContent+'</div>');
            
        });
    
});
</script>