<?php 
$proDetail=$this->proDetail;

$catName            =   $proDetail['cat_name'];
$title              =   $proDetail['name'];
$dNoibat            =   $proDetail['summary_1'];
$dkSudung           =   $proDetail['summary_2'];
$description        =   $proDetail['description'];
$address            =   $proDetail['address'];
$slideImage     ='';
foreach($this->listDetailphoto as $imageName)
{
    $slideImage.='<a href="#" target="_blank"><img width="610" height="330" src="'.PUBLIC_URL.'/files/products/slideshow/'.$imageName['full_image'].'" width="610" height="330"></a>';
    
}
?>
<script>
	$(function(){
		$('#slides').slides({
			preload: true,
			preloadImage: '<?php echo $this->imgUrl ?>/loading.gif',
			play: 5000,
			pause: 2500,
			hoverPause: true
		});
	});
</script>
<!--Main conent-->
    <div id="baseDiv">
        <!--Search-->            
        <?php $this->showSearch($this);?>
        <!--end search-->
        
        <div class="index_border_M">
            <!--Title cateogry -->
            <div class="title_page">
                <div class="title_page_L"></div>
                <div class="title_page_Ce"><?php echo $catName;?></div>
                <div class="title_page_R"></div>
            </div>
            <!--End title category-->
            <br class="clean" />
            <!--End Title category-->
            <div class="product_detail">
            <!--Product detail left-->
                <div class="detail_L">
                    <!--Category Detail-->
                        <h1 class="product_detail_TT"><?php echo $title;?></h1>
                        <!--Slide images-->
                        <div id="silde_images">
                			<img src="<?php echo $this->imgUrl ?>/new-ribbon.png" width="112" height="112" alt="New Ribbon" id="ribbon">
                			<div id="slides">
                				<div class="slides_container">
                					
                					<?php echo $slideImage;?>
                					
                				</div>
                				<!--a href="#" class="prev"><img src="images/arrow-prev.png" width="24" height="43" alt="Arrow Prev"></a>
                				<a href="#" class="next"><img src="images/arrow-next.png" width="24" height="43" alt="Arrow Next"></a-->
                			</div>
                			<img src="<?php echo $this->imgUrl ?>/example-frame.png" width="630" height="400" alt="Example Frame" id="frame" />
                		</div>
                        <!--End slide images-->
                        <!--Dieu kien su dung-->
                        <div class="condition">
                            <div class="condition_T">
                            </div>
                            <div class="condition_Co">
                                <?php echo $dNoibat; ?>
                                <?php echo $dkSudung; ?>
                                <br class="clean" />
                            </div>
                            <div class="condition_B">
                            </div>
                        </div>
                        <!--End dieu kien su dung-->
                        <br class="clean" />
                        <!--introduction product-->
                        <div class="product_detail_Co">
                           <?php echo $description;?>
                        </div>
                        <!--End introduction product-->
                        <?php $this->showFormComment($this,array('type'=>'product')); ?>
                </div>
            <!--End Product detail left-->
                <!--Product detail right-->
                <div class="detail_R">
                    
                    <div class="time">
                        Facebook Share (Anh Nguyên làm lại cái này giúp em với nhé)
                    </div>
                    <div class="time">
                        <p>Thời hạn chấp nhận thẻ:</p>
                        <p class="time_1">Từ 27/02/2012 đến 27/03/2012</p>
                    </div>
                    <div class="address_border">
                        <div class="address">
                            <h3>
                                Địa chỉ:
                            </h3>
                            <?php echo $address;?>
                            <span>
                                <a onclick="ShowMap('/Uploads/Branches/506/439_506_photo.jpg','313 Huỳnh Văn B&#225;nh, Phường 11' + ', Quận Ph&#250; Nhuận' + ', Hồ Ch&#237; Minh')" href="javascript:void(0);"><b><img align="absmiddle" src="Content/images/map.png"/>Bản Đồ</b></a></span>
                            <p class="line1">
                                &nbsp;</p>
                        </div>
                    </div>
                    
                    <div class="title_page">
                        <div class="title_page_L"></div>
                        <div class="title_page_Ce">Địa điểm tương tự</div>
                        <div class="title_page_R">
                        </div>
                    </div>
                    <br class="clean" />
                    <div id="other_product">
                        <?php $this->showProducts($this,array('local'=>'block3','listPro'=>$this->proOrder));?>                        
                    </div>
                    <br class="clean" />
                </div>
                <!--End Product detail right-->
            </div>
        </div>
        <div class="index_border_B"></div>
    </div>
    <!--End main content-->