<?php
$info=$this->proDetail;
$description=$this->cmsConvertDbToView($info['description']);

$tab1_name=$tab2_name=$tab3_name=$tab4_name='';
if($info['summary_1'])
{
    $tab1_name='<a class="active" href="#">'.$info['name'].'</a>';    
    $tab1='<div class="content active">'.$this->cmsConvertDbToView($info['summary_1']).'</div>';
}    
if($info['summary_2'])
{
    $tab2_name='<a class="" href="#">'.'ĐẶC TRƯNG SẢN PHẨM'.'</a>';
    $tab2='<div class="content">'.$this->cmsConvertDbToView($info['summary_2']).'</div>';
}    
if($info['summary_3'])
{
    $tab3_name='<a class="" href="#">'.'KHÁC BIỆT'.'</a>';    
    $tab3='<div class="content">'.$this->cmsConvertDbToView($info['summary_3']).'</div>';
}    
if($info['summary_4'])
{
    $tab4_name='<a class="" href="#">'.'THÀNH PHẦN'.'</a>';    
    $tab4='<div class="content">'.$this->cmsConvertDbToView($info['summary_4']).'</div>';
}
if($info['summary_5'])
{
    $tab5_name='<a class="" href="#">'.'HỒ SƠ CÔNG BỐ'.'</a>';    
    $tab5='<div class="content">'.$this->cmsConvertDbToView($info['summary_5']).'</div>';
}


$listPhoto='';
      
foreach($this->listDetailphoto as $infoIMG)
{
    $product_image	= PUBLIC_URL.'/files/products/slideshow/'.$infoIMG['full_image'];       
    $listPhoto.= '  <li>
				<img src="'.$product_image.'" alt="" link="#"/>
				<div class="slider-banner">
					<br><br><br><br><br><br><br><br><br>
					
				</div>
			</li>';
}
if($listPhoto)
{
    $listPhoto='<div class="main-slider"><ul class="items">'.$listPhoto.'</ul></div>';
}
?>
<div id="warrap_product_detail">
    <div id="content_secsion">
        <!-- Content -->
    	<section class="padcontent2">
    		<div class="container_12">
    			<div class="wrapper">
    				<div class="grid_8">
                        <?php echo $this->Showpath($this);	?>
                        <div class="clear"></div>
    					<div class="wrapper indent">
                            <div id="product_detail_indent">
        					   <?php echo $listPhoto;?>
                                <div id="product_detail_item">
                                
                                    <?php 
                                    if($tab1.$tab2.$tab3.$tab4!='')
                                    {
                                    ?>
                                    <script type="text/javascript">
                                        $(document).ready(function(e) {
                                        	$('.tabs-wrap .tabs-head a').click(function(e){
                                        		e.preventDefault();
                                        		$(this).blur();
                                        		$(this).siblings().removeClass('active');
                                        		$(this).addClass('active');
                                        		$('.tabs-wrap .tabs-contents .content').removeClass('active');				
                                        		$($('.tabs-wrap .tabs-contents .content')[$(this).index()]).addClass('active');
                                        	});
                                        	
                                        });
                                        
                                        </script>
                                    <div class="tabs-wrap account-settings">
                                        <div class="tabs-head">
                                			<?php echo $tab1_name.$tab2_name.$tab3_name.$tab4_name.$tab5_name;?>
                                		</div>
                                        <div class="tabs-contents shadow light">
                                            <?php echo $tab1.$tab2.$tab3.$tab4.$tab5;?>
                                        </div>
                                    </div>
                                    <?php } ?>
                                </div>
                                <div id="product_detail_content">
                                    <?php echo $description;?>
                                </div>	
                            </div>
    					</div>
    				</div>
    				<div class="grid_4">
    					<!--h4>Featured Services</h4-->
    					<?php 
                        $this->showProducts($this,array('local'=>'category'));
                        ?>
    					<div class="padline3"><div class="lineH"></div></div>
                        <?php 
                        //$this->showProducts($this,array('local'=>'new_product'));
                        ?>
                        
                        <!--Quang cao-->
                        <?php $this->ShowADSByModuleAndPosition('right',$this->arrParam['module'],$this);?>
    				</div>
    			</div>
    		</div>
    	</section>
    </div>
</div>