<?php

$info=$this->proDetail;

$description=$this->cmsConvertDbToView($info['description']);
$summary=$this->cmsConvertDbToView($info['summary']);

$title=$this->cmsConvertDbToView($info['name']);
$listPhoto='';
      
foreach($this->listDetailphoto as $infoIMG)
{
    $product_image	= PUBLIC_URL.'/files/products/slideshow/'.$infoIMG['full_image'];       
    /*$listPhoto.= '  <li>
				<img src="'.$product_image.'" alt="" link="#"/>
				<div class="slider-banner">
					<br><br><br><br><br><br><br><br><br>
					
				</div>
			</li>';*/
    $listPhoto.='<div class="views_jqfx_cycle_slide views_jqfx_slide views-row-1 views-row-odd" id="views_jqfx_cycle_div_slider-block_0">
                    <div class="views-row views-row-0 views-row-first views-row-odd">
                        <div class="views-field views-field-field-slide-image">        
                            <div class="field-content"><img src="'.$product_image.'" alt="" /></div>  
                        </div>'.  
                        /*<div class="views-field views-field-body-1">        
                            <div class="field-content">
                                <div class="slider-title"><a href="#?q=node/50">A driving force</a></div>
                                    <div class="slider-body"><p>in your business!</p></div>
                                    <div class="slider-node"><a href="#?q=node/50">more</a></div>
                            </div>  
                        </div>*/
                        '
                    </div>
                </div>';                                    
}
if($listPhoto)
{
    $listPhoto='<div class="section-3 clearfix">
                    <div class="region region-header">
                        <div id="block-views-slider-block" class="block block-views block-even">
                            <div class="content">
                                <div class="view view-slider view-id-slider view-display-id-block view-dom-id-db396005eb80e0a4042ddc5db4af437f">
                                    <div class="view-content">
                                        <div class="view-grouping">
                                            <div class="view-grouping-header"></div>
                                            <div class="view-grouping-content">
                                                <div class="skin-default">
                                                    <div id="views_jqfx_cycle_main_slider-block" class="views_jqfx_cycle_main views jqfx_main">
                                                        <div id="views_jqfx_cycle_teaser_section_slider-block" class="views_jqfx_cycle_teaser_section clearfix">
                                                        '.$listPhoto.'
                                                        </div>
                                                    </div>
                                                    <div class="views-jqfx-controls-bottom clearfix">
                                                        <div class="views_jqfx_cycle_pager views_jqfx_pager_numbered" id="views_jqfx_cycle_pager_slider-block"></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>    
                                    </div>
                                </div>  
                            </div><!-- /.content -->
                    </div><!-- /.block -->  
                </div>
            </div><!-- /.section -->';
}
?>

<?php /* ?>
<div id="warrap_product_detail">
    <div id="content_secsion">
        <!-- Content -->
    	<section class="padcontent2">
    		<div class="container_12">
    			<div class="wrapper">
    				<div class="grid_8">
                        <?php echo $this->Showpath($this);	?>
                        <div class="clear"></div>
    					<div class="wrapper indent">
                            <div id="product_detail_indent">
        					   <?php echo $listPhoto;?>
                                <div id="product_detail_item">
                                
                                    <?php 
                                    if($tab1.$tab2.$tab3.$tab4!='')
                                    {
                                    ?>
                                    <script type="text/javascript">
                                        $(document).ready(function(e) {
                                        	$('.tabs-wrap .tabs-head a').click(function(e){
                                        		e.preventDefault();
                                        		$(this).blur();
                                        		$(this).siblings().removeClass('active');
                                        		$(this).addClass('active');
                                        		$('.tabs-wrap .tabs-contents .content').removeClass('active');				
                                        		$($('.tabs-wrap .tabs-contents .content')[$(this).index()]).addClass('active');
                                        	});
                                        	
                                        });
                                        
                                        </script>
                                    <div class="tabs-wrap account-settings">
                                        <div class="tabs-head">
                                			<?php echo $tab1_name.$tab2_name.$tab3_name.$tab4_name.$tab5_name;?>
                                		</div>
                                        <div class="tabs-contents shadow light">
                                            <?php echo $tab1.$tab2.$tab3.$tab4.$tab5;?>
                                        </div>
                                    </div>
                                    <?php } ?>
                                </div>
                                <div id="product_detail_content">
                                    <?php echo $description;?>
                                </div>	
                            </div>
    					</div>
    				</div>
    				<div class="grid_4">
    					<!--h4>Featured Services</h4-->
    					<?php 
                        $this->showProducts($this,array('local'=>'category'));
                        ?>
    					<div class="padline3"><div class="lineH"></div></div>
                        <?php 
                        $this->showProducts($this,array('local'=>'new_product'));
                        ?>
                        
                        <!--Quang cao-->
                        <?php $this->ShowADSByModuleAndPosition('right',$this->arrParam['module'],$this);?>
    				</div>
    			</div>
    		</div>
    	</section>
    </div>
</div>
<?php */ ?>











<div id="main-wrapper">
    <div class="clearfix" id="main">
        <div role="complementary" class="column sidebar" id="sidebar-second">
            <div class="section">
                <div class="region region-sidebar-second">
                    <section class="block block-blog block-even" id="block-blog-recent">
                        <?php 
                        $this->showProducts($this,array('local'=>'category'));
                        ?>
       					<div class="padline3"><div class="lineH"></div></div>
                    </section>
                    <section class="block block-blog block-even" id="block-blog-recent">
                        <?php 
                        $this->showProducts($this,array('local'=>'new_product'));
                        ?><!-- /.content -->
                    </section><!-- /.block -->  
                </div>
            </div><!-- /.section -->
        </div><!-- /#sidebar-second -->
        <div role="main" class="column" id="content">
            <div class="section">
                <!--h1 id="page-title" class="title">Blogs</h1-->
                <?php echo $this->Showpath($this);	?>
                <div class="region region-content">
                    <div class="block block-system block-odd" id="block-system-main">
                        <div class="content">
							<h1 class="news_title"><?php echo $title;?></h1>
                                    <?php echo $listPhoto;?>                                         
                            <div class="product_content">
                                    <?php echo $summary;?>
                                    <?php echo $description;?>
                            </div>
                        </div>  
                    </div><!-- /.content -->
                </div><!-- /.block -->
            </div>
        </div><!-- /.section -->
    </div><!-- /#content -->
</div><!-- /#main -->