
 <div class="main-container col2-right-layout">
<?php 
$cache=Zendvn_Cache::getCacheObject('productdetailindex');
//$cacheManager=Zend_Registry::get('cacheManager',$cache);

$keyCache='view_product_detail_'.$this->proDetail['id'];
if (!($cache->start($keyCache))) {
 
?>    
            <div class="main">
               
                <div class="col-main">
                    <div class="wrapper_col-inner">
<?php
$info=$this->proDetail;
$summary=strip_tags($this->cmsConvertDbToView($info['summary']));
$title=$this->cmsConvertDbToView($info['name']);
$price=number_format($info['price']);

$description=$this->cmsConvertDbToView($info['description']);
/*
$tab1_name=$tab2_name=$tab3_name=$tab4_name='';
if($info['summary_1'])
{
    $tab1_name='<a class="active" href="#">'.$info['name'].'</a>';    
    $tab1='<div class="content active">'.$this->cmsConvertDbToView($info['summary_1']).'</div>';
}    
if($info['summary_2'])
{
    $tab2_name='<a class="" href="#">'.'ĐẶC TRƯNG SẢN PHẨM'.'</a>';
    $tab2='<div class="content">'.$this->cmsConvertDbToView($info['summary_2']).'</div>';
}    
if($info['summary_3'])
{
    $tab3_name='<a class="" href="#">'.'KHÁC BIỆT'.'</a>';    
    $tab3='<div class="content">'.$this->cmsConvertDbToView($info['summary_3']).'</div>';
}    
if($info['summary_4'])
{
    $tab4_name='<a class="" href="#">'.'THÀNH PHẦN'.'</a>';    
    $tab4='<div class="content">'.$this->cmsConvertDbToView($info['summary_4']).'</div>';
}
if($info['summary_5'])
{
    $tab5_name='<a class="" href="#">'.'HỒ SƠ CÔNG BỐ'.'</a>';    
    $tab5='<div class="content">'.$this->cmsConvertDbToView($info['summary_5']).'</div>';
}
*/
$product_image  = PUBLIC_URL.'/files/products/image/'.$info['image'];

$rw=new Zendvn_View_Helper_CmsRewriteLink();


$arrValue['name']=$rw->noSign($info['name']);
$arrValue['id']=$info['id'];
$arrValue['cat_name']=$rw->noSign($this->categoryDetail['name']);
$arrValue['cat_id']=$this->categoryDetail['id'];
$linkCurrent   = $this->serverUrl($this->url($arrValue,'product-detail-index'));


?>
                         <div class="breadcrumbs">
                            <ul>
                                <li class="home">
                                    <a href="<?php echo DOMAIN_NAME;?>" title="Go to Home Page">Trang chủ</a>
                                        <span> &nbsp; </span>
                                </li>
                                <li class="category53">
                                    <?php
                                        $rw=new Zendvn_View_Helper_CmsRewriteLink();
                                        $link   = $this->serverUrl($this->url(array(
                                            'cat_id'=>$this->categoryDetail['id'],
                                            'cat_name'=>$rw->noSign($this->categoryDetail['name'])
                                        ),'product-index-list'));
                                    ?>
                                    <a href="<?php echo $link;?>" title="<?php echo $this->categoryDetail['name'];?>"><?php echo $this->categoryDetail['name'];?></a>
                                    <span> &nbsp; </span>
                                </li>
                                <li class="product">
                                    <strong><?php echo $title;?></strong>
                                </li>
                            </ul>
                        </div>
                                               
<div id="messages_product_view"></div>
<div class="product-view">
    <div class="product-essential">
    <form action="" method="post" id="product_addtocart_form" enctype="multipart/form-data">
        <div class="no-display">
            <input type="hidden" name="product" value="195" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>

        <div class="product-shop">
            <div class="product-name">
                <h1><?php echo $title;?></h1>
            </div>
            <p><?php echo $this->ShowFbLike();?></p>

            <div class="price-box">
                <span class="regular-price" id="product-price-195">
                    <span class="price"><?php echo $price;?> vnđ</span>                
                </span>                        
            </div>

            <div class="short-description">
                <h2>Mô tả</h2>
                <div class="std">
                    <?php echo $summary;?>
                </div>
            </div>
            <div class="clearer"></div>
                         
        </div>

        <div class="product-img-box">
            <p class="product-image">
            
                    <img src="<?php echo $product_image;?>" alt='' title="Sweetheart Roses with Vase " />
            
            </p>
            
</div>

       
    </form>
    
    </div>

    <div class="product-collateral">
        <div class="box-collateral box-description">
            <h2>Chi tiết sản phẩm</h2>
            <div class="std">
                <?php echo $description;?>
            </div>
        </div>



        <div class="box-collateral box-description">
            <h2>Phản hồi của khách hàng</h2>
            <div class="std">
                <div id="fb-root"></div>
                <script>(function(d, s, id) {
                  var js, fjs = d.getElementsByTagName(s)[0];
                  if (d.getElementById(id)) return;
                  js = d.createElement(s); js.id = id;
                  js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1&appId=305298686265541";
                  fjs.parentNode.insertBefore(js, fjs);
                }(document, 'script', 'facebook-jssdk'));</script>
                <div class="fb-comments" data-href="<?php echo $linkCurrent;?>" data-width="635" data-num-posts="10"></div>
            </div>
        </div>



        <div class="box-collateral box-up-sell">
    <h2>Các sản phẩm khác</h2>    
    <table class="products-grid" id="upsell-product-table">
         <tr>
            <td>
            <?php  if($this->listProducts[0]) $this->showProducts($this,array('local'=>'block_item','info'=>$this->listProducts[0]));?>    
            </td>
            <td>
            <?php  if($this->listProducts[1]) $this->showProducts($this,array('local'=>'block_item','info'=>$this->listProducts[1]));?>    
            </td>
            <td>
            <?php  if($this->listProducts[2]) $this->showProducts($this,array('local'=>'block_item','info'=>$this->listProducts[2]));?>    
            </td>
        </tr>
    </table>
    <script type="text/javascript">decorateTable('upsell-product-table')</script>
</div>
    
    </div>
</div>


            </div>
            <div class="col-inner_bottom"></div>
<?php
 
    $cache->end(); // output buffering ends
 
}
 
?>            
        </div>
    <div class="col-right sidebar">
        <?php $this->showWidget($this,array('widget'=>'minisearch'));?>
        <?php $this->showWidget($this,array('widget'=>'fanpage'));?>
        <?php $this->showWidget($this,array('widget'=>'contact'));?>
        <?php $this->showWidget($this,array('widget'=>'music'));?>
    </div>
            </div>
        </div>



