<form name="appForm" method="post" action="">



                        <?php echo $this->render('admin-weblink/toolbar/index.php')?>
                        <div class="clr"></div>
                         <?php echo $this->render('admin-weblink/sublink/index.php')?>

                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
						<div id="adminfieldset">
                             <div id="errors">
                             	Bạn có chắc muốn xóa phần tử này không?
                             </div>
								
								
                                
							</div>
							
                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>