<?php 

    $options 		= array('Inactive','Active');
	$status 		= $this->formRadio('status',$this->Item['status'],null,$options, ' ');
    
	$options = $this->slbPrivileges;
	$slbPrivileges = $this->formSelect('privileges_id',$this->Item['privileges'],array('multiple'=>'multiple','size'=>'10'),$options);
	

    $options = $this->slbGroup;
	$slbGroup = $this->formSelect('group_id',$this->Item['group_id'],null,$options);

	if(!empty($this->errors)){
		$errors = $this->formErrors($this->errors );
	}
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data" >



                        <?php echo $this->render('admin-permission/toolbar/index.php')?>
                        <div class="clr"></div>
                         <?php echo $this->render('admin-permission/sublink/index.php')?>

                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
						<div id="adminfieldset">
                             <div class="adminheader">Detail</div>
										
                         		<?php 
                         		if(!empty($this->errors)){
                         			if($this->errors[0]=="success"){
                         				echo '<div id="success">';
										echo '<pre>';
											print_r($errors);
										echo '</pre>';
										echo '</div>';
                         				
                         			}
                         			else{
	                         			echo '<div id="errors">';
										echo '<pre>';
											print_r($errors);
										echo '</pre>';
										echo '</div>';
                         			}
								}
								?>
								
                                
                                <div id="row">
                                    <div class="label">Group:</div>
                                    <?php echo $slbGroup;?>			
                                </div>
                                <div class="clr"></div>
                                
                                <div id="row">
                                    <div class="label">Permission:</div>
                                    <?php echo $slbPrivileges;?>			
                                </div>
                                <div class="clr"></div>
                                
                                <div id="row">
                                    <div class="label">Status:</div>
                                    <?php echo $status;?>			
                                </div>
                                <div class="clr"></div>
                              
                                
							</div>
							
                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>