<?php 

	$group_name 	= $this->Item['group_name'];
	$avatar 		= $this->Item['avatar'];
	$ranking		= $this->Item['ranking'];
	
	$group_acp 		= $this->Item['group_acp'];
	$group_default 	= $this->Item['group_default'];
	
	$created_by 	= $this->Item['created_by'];
	$created	 	= $this->Item['created'];
	$modified_by 	= $this->Item['modified_by'];
	$modified	 	= $this->Item['modified'];
	
	$status 		= $this->Item['status'];
	$order 			= $this->Item['order'];
?>
<form name="appForm" method="post" action="">



                        <?php echo $this->render('admin-permission/toolbar/index.php')?>
                        <div class="clr"></div>
                         <?php echo $this->render('admin-permission/sublink/index.php')?>

                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
						<div id="adminfieldset">
                             <div id="errors">
                             	Ban co chac chan muon xoa phan tu nay hay khong?
                             </div>
								
								
                                
							</div>
							
                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>