<?php
	
	$strDay = '<select name="day" id="day"  data-icon="false">';
    for($i=1;$i<=31;$i++)
    {
        if($i == date('d'))
        {
            $strSelected ='selected="selected"';
        }
        else
        {
            $strSelected ='';
        }
        if($i<10)
        {
            $ii = '0'.$i;
        }
        else
        {
            $ii = $i;
        }
        $strDay.='<option '.$strSelected.' value="'.$ii.'">'.$ii.'</option>';
    }
    $strDay .= '</select>';
    $strMonth = '<select name="month" id="month"  data-icon="false">';
    for($i=1;$i<=12;$i++)
    {
        if($i == date('m'))
        {
            $strSelected ='selected="selected"';
        }
        else
        {
            $strSelected ='';
        }
        if($i<10)
        {
            $ii = '0'.$i;
        }
        else
        {
            $ii = $i;
        }
        $strMonth.='<option '.$strSelected.' value="'.$ii.'">'.$ii.'</option>';
    }
    $strMonth .= '</select>';
    
    $strYear = '<select name="year" id="year" data-icon="false">';
    for($i=date('Y');$i<=2015;$i++)
    {
        if($i == date('Y'))
        {
            $strSelected ='selected="selected"';
        }
        else
        {
            $strSelected ='';
        }
        $strYear.='<option '.$strSelected.' value="'.$i.'">'.$i.'</option>';
    }
    $strYear .= '</select>';
    $strLocation = '<select name="location" id="location" data-icon="false">';
    foreach($this->listLocation as $key => $value)
    {
        if($key == 'tphcm')
        {
            $strSelected ='selected="selected"';
        }
        else
        {
            $strSelected ='';
        }
        $strLocation.='<option '.$strSelected.' value="'.$key.'">'.$value.'</option>';
    }
    $strLocation .= '</select>';


?>
<div data-role="page" class="jqm-demos ui-responsive-panel" id="panel-fixed-thoitiet">

    <div data-role="header" data-theme="c" >
        <h1>Lịch chiếu phim</h1>
        <?php echo $this->showCategory($this);?>
        <a href="<?php echo $this->baseUrl('');?>" data-icon="home" data-iconpos="notext" data-transition="slide">Home</a>
    </div><!-- /header -->

    <div data-role="content" class="jqm-content">
		<form>
		<fieldset data-role="controlgroup" data-type="horizontal" data-mini="true">
		    <?php echo $strDay;?>
		    <?php echo $strMonth;?>
		    <?php echo $strYear;?>
		
		    <?php echo $strLocation;?>
            <a data-mini="true" id="showlist" onclick="return false;" href="#" data-role="button" data-icon="search" data-theme="b" data-iconpos="right" data-inline="true">Xem</a>		
		    </fieldset>
		     
		    
		
		</form>
		
		<div id="chanel-content">
            <div id="ajax-flag" class="lichchieuphim" style="display: none;"><img src="<?php echo $this->baseUrl('public/templates/public/online/images/loading.gif') ?>" /></div>
            <div id="ha-noi" class="lichchieuphim" style="display: none;"><?php echo $this->lichchieuphim['ha-noi'];?></div>
            <div id="tphcm" class="lichchieuphim" ><?php echo $this->lichchieuphim['tphcm'];?></div>
            <div id="hai-phong" class="lichchieuphim" style="display: none;"><?php echo $this->lichchieuphim['hai-phong'];?></div>
            <div id="da-nang" class="lichchieuphim" style="display: none;"><?php echo $this->lichchieuphim['da-nang'];?></div>
        </div>
	    <script>
            $(document).ready(function() 
            {
                var _curentLocation = 'tphcm';
                var n = new Date();
                var month = n.getMonth()+1;
                var day = n.getDate();
                var _curentDate = (day<10 ? '0' : '') + day + '-' + (month<10 ? '0' : '') + month + '-' + n.getFullYear();
                $('#showlist').click(function()
                {
                    var day = $('select[name=day] option:selected').val();
                    var month = $('select[name=month] option:selected').val();
                    var year = $('select[name=year] option:selected').val();
                    var date = day + '-' + month + '-' + year;
                    var location = $('select[name=location] option:selected').val();
                    if(date == _curentDate)
                    {
                        if(location == _curentLocation)
                        {
                            return;
                        }
                        else
                        {
                            $('#' + _curentLocation).hide();
                            $('#' + location).fadeIn(1000);
                            _curentLocation = location;
                            _curentDate = date;
                        }
                        return;
                    }
                    $('#ajax-flag').show();
                    $('#' + _curentLocation).hide();
                    $.ajax({
                          type: 'POST',
                          url:'<?php echo $this->baseUrl('')?>service/lichchieuphim/getlichchieuphim',
                          data: {date:date},
                          dataType:'json',
                          success:function(data){ 
                            if(parseInt(data.rs) == 1)
                            {
                                //alert(data.hanoi);
                                $('#ha-noi').html(data.hanoi);
                                $('#tphcm').html(data.tphcm);
                                $('#da-nang').html(data.danang);
                                $('#hai-phong').html(data.haiphong);
                                $('#chanel-content table').attr('cellpadding','0');
                                $('#chanel-content table').attr('cellspacing','0');
                                $('#chanel-content table').attr('border','0');
                                $('#chanel-content table').attr('width','100%');
                                $('#' + _curentLocation).hide();
                                $('#' + location).fadeIn(1000);
                                _curentLocation = location;
                                _curentDate = date;
                                $('#ajax-flag').hide(); 
                                return false;            
                            }
                            else
                            {
                                
                            }
                          }   
                        });        
                });
                //alert(_curentDate);
                //alert($('#chanel-content table tr td:eq(2)').html());
                $('#chanel-content table').attr('cellpadding','0');
                $('#chanel-content table').attr('cellspacing','0');
                $('#chanel-content table').attr('border','0');
                $('#chanel-content table').attr('width','100%');
                /*$('#chanel-content table').addClass('ta1');
                $('#chanel-content table th').addClass('pt_title');
                $('#chanel-content table tr:even').addClass('pt_mau2');*/
            });
        </script>
	   	
    </div><!-- /content -->

	
	<?php echo $this->showCategory($this,'service');?>
	
</div><!-- /page -->
