<?php
	$listLocation = $this->listLocation;
    //echo count($listLocation);
    $strAnotherCity = '';
	$selectTinh='<label for="tinh"><strong>Tỉnh - Thành phố</strong>: </label><select name="tinh" onChange="showInfoWeather(this.value)" id="tinh">';
    $selectTinh.='<option value="all">Xem tất cả</option>';
	foreach ($this->listLocation as $k => $v) {
		$selectTinh.='<option value="'.$k.'">'.$v.'</option>';	
        $strAnotherCity .= '<li><a href="#" title="" onclick="changeCity(\''.$k.'\')">'.mb_strtoupper($listLocation[$k],'UTF-8').'</a></li>';	
	}
	
	$selectTinh.='</select>';

	$thoitiet='';
    $arrDefaultShow = array('44','58','88','92','56');
    $first = false;
    $arrDay = array();
    $strInfo .= '<span '.$hide.' id="weather-info-all">DỰ BÁO THỜI TIẾT CÁC TỈNH</span>';  
	foreach ($this->thoitiet as $key => $value) 
	{
	   if(!$first)
       {
            array_push($arrDay,$value[0]['day']);
            array_push($arrDay,$value[1]['day']);
            array_push($arrDay,$value[2]['day']);
            $first = true;
       }
	    if(in_array($key,$arrDefaultShow))
        {
            $strShow ='';
        }
        else
        {
            $strShow ='display:none';
            
        }
        $hide ='style="display:none"';
        $strInfo .= '<span '.$hide.' id="weather-info-'.$key.'">DỰ BÁO THỜI TIẾT '. mb_strtoupper($listLocation[$key],'UTF-8').'</span>';
        $thoitiet .= '<tr class="info_weather"id="info-weather-'.$key.'" style="'.$strShow.'">
                        <td class="location">'.mb_strtoupper($listLocation[$key],'UTF-8').'</td>                       
                        <td class="info_weather_col">
                            <img src="'.$value[0]['image'].'">
                                <h3 class="blue">'.$value[0]['t_min'].' - '.$value[0]['t_max'].'</h3>
                                <p class="forecast">'.$value[0]['status'].'</p>
                        </td>                            
                        <td class="info_weather_col">
                            <img src="'.$value[1]['image'].'">
                                <h3 class="blue">'.$value[1]['t_min'].' - '.$value[1]['t_max'].'</h3>
                                <p class="forecast">'.$value[1]['status'].'</p>
                        </td>
                        <td class="info_weather_col">
                            <img src="'.$value[2]['image'].'">
                                <h3 class="blue">'.$value[2]['t_min'].' - '.$value[2]['t_max'].'</h3>
                                <p class="forecast">'.$value[2]['status'].'</p>
                        </td>
                    </tr>';
	}
    //echo '<pre>';
    //var_dump($this->listLocation);
    //echo "</pre>";
    //echo $thoitiet;
?>
<div id="category">
    <div class="wrapper">
        <div id="cat-content">
            <div id="cat-left">
                <div id="category-detail">
                    <div class="nav_link">
                        <h2><span style="float: left;margin-right: 5px;"><a href="<?php echo DOMAIN_NAME; ?>" title="">TRANG CHỦ</a></span> <span style="float: left;margin-right: 6px; margin-top:1px"><img src="<?php echo DOMAIN_NAME;?>public/templates/public/online/images/breadcrumb-right.png" /></span> <span style="float: left;">Thời tiết</span></h2>
                    </div>
                    <div class="category-detail">
                        <div class="clr">
                                <div class="thoitiet-title" style="float: left;"><?php echo $strInfo;?></div>
                                <div style="float: right; padding-top:10px; padding-left:4px;"><strong> - Nguồn: </strong> <a href="http://www.nchmf.gov.vn/web/vi-VN/43/Default.aspx" target="_blank">Khí tượng thủy văn</a></div>
                                <div style="float: right; padding-top:10px;"><?php echo $selectTinh;?></div>
                                
                            </div>
                        <table cellpadding="7" cellspacing="0" class="table">
                            <tr class="day_weather">
                                <td class="location"><h3 class="blue">THỜI TIẾT TẠI</h3></td>
                                <td class="info_weather_col"><h3><?php echo $arrDay[0];?></h3></td>
                                <td class="info_weather_col"><h3><?php echo $arrDay[1];?></h3></td>
                                <td class="info_weather_col"><h3><?php echo $arrDay[2];?></h3></td>
                            </tr>
                            <?php echo $thoitiet;?>
                        </table>
                    </div>
                </div>
            </div>
            <div id="cat-right">
                <?php $this->ShowMenuRight($this);?>
                <?php $this->ShowTinThoitiet($this)?>
                <?php $this->ShowCopyRight($this);?>
            </div>
        </div>
    </div>
</div>