<?php
	
	$selectTinh='<label for="tinh">Tinh</label><select name="tinh" id="tinh">';
	foreach ($this->listLocation as $k => $v) {		
		$selectTinh.='<option value="'.$k.'">'.$v.'</option>';		
	}
	
	$selectTinh.='</select>';

	$thoitiet='';
	foreach ($this->thoitiet as $key => $value) 
	{
		$thoitiet.='
		<tbody id="tinh_body_'.$key.'" style="display:none;" class="thoitietinfo">
		    <tr>
              <td style="text-align:center">
                <strong>'.$value['0']['day'].'</strong><br>
                <img src="'.$value[0]['image'].'"><br>
                Nhiệt độ: '.$value[0]['t_min'].' - '.$value[0]['t_max'].'<br>'
                .$value[0]['status'].'
              </td>
              <td style="text-align:center">
                <strong>'.$value['1']['day'].'</strong><br>
                <img src="'.$value[1]['image'].'"><br>
                Nhiệt độ: '.$value[1]['t_min'].' - '.$value[1]['t_max'].'<br>'
                .$value[1]['status'].'
              </td>
              <td style="text-align:center">
                <strong>'.$value['2']['day'].'</strong><br>
                <img src="'.$value[2]['image'].'"><br>
                Nhiệt độ: '.$value[2]['t_min'].' - '.$value[2]['t_max'].'<br>'
                .$value[2]['status'].'
              </td>
		    </tr>    
		</tbody>
		';
	}


?>
<div data-role="page" class="jqm-demos ui-responsive-panel" id="panel-fixed-thoitiet">

    <div data-role="header" data-theme="c" >
        <h1>Thời tiết</h1>
        <?php echo $this->showCategory($this);?>
        <a href="<?php echo $this->baseUrl('');?>" data-icon="home" data-iconpos="notext" data-transition="slide">Home</a>
    </div><!-- /header -->

    <div data-role="content" class="jqm-content">
		<form>
		<fieldset data-role="controlgroup" data-type="horizontal" data-mini="true">
		    <legend>Tỉnh thành</legend>
		    <?php //echo $selectKhuvuc;?>
		    <?php echo $selectTinh;?>
		</fieldset>
		</form>
		<table data-role="table" id="movie-table" data-mode="reflow" class="ui-responsive table-stroke">
			<thead  style="display:none;">
			    <tr>		      		      
			      <th data-priority="1"></th>
			      <th data-priority="2"></th>
			      <th data-priority="3"></th>
			    </tr>
			</thead>
		  <?php echo $thoitiet;?>
		</table>
        <div style="float: right; padding-top:10px; padding-left:4px;"><strong>Nguồn: </strong> <a href="http://www.nchmf.gov.vn/web/vi-VN/43/Default.aspx" target="_blank">Khí tượng thủy văn</a></div>
    </div><!-- /content -->

	
	<?php echo $this->showCategory($this,'service');?>
	
</div><!-- /page -->
<script>

$(document).ready(function(){
	$("#tinh").change(function(){
		var idTinh=$(this).val();
		$(".thoitietinfo").hide();
		//$("#tinh_header_"+idTinh).show();
		$("#tinh_body_"+idTinh).show();
	});
	$("#tinh").change();
});
</script>