<?php 
	
	$ssFilter = $this->arrParam['ssFilter'];
	$action_link 	= $this->baseUrl($this->currentController . '/filter/type/order');
	$lbip 			= $this->cmsLinkSort('IP','n.ip',$ssFilter,
										$this->imgUrl . '/icon',$action_link);
	$lbbrowser 			= $this->cmsLinkSort('Browser','n.browser',$ssFilter,
										$this->imgUrl . '/icon',$action_link);
	
	$lblStatus		= $this->cmsLinkSort('Status','n.status',$ssFilter,
										$this->imgUrl . '/icon',$action_link);											
	
	$lblTimelogin= $this->cmsLinkSort('Login Time','n.timelogin',$ssFilter,
										$this->imgUrl . '/icon',$action_link);
										
	$lblUserName 		= $this->cmsLinkSort('Username','u.user_name',$ssFilter,
										$this->imgUrl . '/icon',$action_link);																	

	$lblID 		= $this->cmsLinkSort('ID','n.id',$ssFilter,
										$this->imgUrl . '/icon',$action_link);

	
	//-------------------CREATE DATE FILTER ------------------------
	$dateFrom	= '  -  Date from: '.$this->cmsDatepicker('date_from',$ssFilter['date_from'],array('class'=>'txtshort'), $this,'birthday');
	$dateTo		= ' - Date to: '.$this->cmsDatepicker('date_to',$ssFilter['date_to'],array('class'=>'txtshort'), $this,'birthday');
	$linkSearch = $this->baseUrl($this->currentController . '/filter/type/date/key/1');
	$btnSearch = $this->formButton('search-now','Filter by date',
									array('onclick'=>"OnSubmitForm('" . $linkSearch . "')"));
	$linkResetSearch = $this->baseUrl($this->currentController . '/filter/type/date/key/0');							
	$btnResetSearch = $this->formButton('clear-keywords','Show all',
									array('onclick'=>"OnSubmitForm('" . $linkResetSearch . "')"));
	$strDateSearch = $dateFrom . ' ' . $dateTo . ' ' . $btnSearch . ' ' . $btnResetSearch;	
	
	//CREATE SEARCH AREA
	$keywords = $this->formText('keywords',$ssFilter['keywords'],array('class'=>'txtshort'));
	$linkSearch = $this->baseUrl($this->currentController . '/filter/type/search/key/1');
	$btnSearch = $this->formButton('search-now','Search IP',
									array('onclick'=>"OnSubmitForm('" . $linkSearch . "')"));
	$linkResetSearch = $this->baseUrl($this->currentController . '/filter/type/search/key/0');							
	$btnResetSearch = $this->formButton('clear-keywords','Clear',
									array('onclick'=>"OnSubmitForm('" . $linkResetSearch . "')"));	
	 $strSearch = $keywords . ' ' . $btnSearch . ' ' . $btnResetSearch;	
	 $this->view->errors;															
?>
<form name="appForm" method="post" action="">



                        <?php echo $this->render('admin-file-log/toolbar/index.php')?>
                        <div class="clr"></div>
                         <?php echo $this->render('admin-file-log/sublink/index.php')?>

                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
								<div id="filters">
									<div style="float:left;">
										<?php echo $strSearch . $strDateSearch;?>
									</div>
									<div  style="float:right;">
										
									</div>
									<div class="clr"></div>
								</div>	

                                <!-- Area 4: In du lieu lay tu database -->
                                <table class="adminlist">
                                    <thead>
                                        <tr>
                                            <th width="43" >
                                            	<input type="checkbox" name="checkbox" id="checkbox" onclick="checkedAll()">
                                           	</th>
                                            <th><?php echo $lbbrowser;?></th>
                                            
                                            <th width="100"><?php echo $lbip;?></th>                                           
                                            <th width="89"><?php echo $lblStatus;?></th>                                           
                                            <th width="120"><?php echo $lblTimelogin;?></th>						
                                            <th width="100"><?php echo $lblUserName;?></th>                                            
                                            <th width="90">Control</th>

                                            <th width="34"><?php echo $lblID;?></th>
                                        </tr>
                                    </thead>
									<?php 
										foreach($this->Items as $key => $val){
											$id 			= $val['id'];
											$ip				= $val['ip'];
											$browser		= $val['browser'];
											
											$timelogin 		= $val['timelogin'];
											$username 		= $val['username'];
											
											$status 		= $val['status'];
											if($status == 1){	
												$linkStatus = $this->baseUrl($this->currentController . '/status/type/0/id/' . $id . '/page/' . $this->arrParam['page']);											
												$status = $this->cmsIconButton('Active', $this->imgUrl . '/icon/active.png',$linkStatus);
											}else{
												$linkStatus = $this->baseUrl($this->currentController . '/status/type/1/id/' . $id . '/page/' . $this->arrParam['page']);
												$status = $this->cmsIconButton('INactive', $this->imgUrl . '/icon/inactive.png',$linkStatus);
											}											
											
											
											
											
											
											$linkInfo		= $this->baseUrl($this->currentController . '/info/id/' . $id);											
											$btnInfo		= $this->cmsIconButton('View Item',$this->imgUrl . '/icon_info.png',$linkInfo);
											
											$linkDelete		= $this->baseUrl($this->currentController . '/delete/id/' . $id);
											$btnDelete		= $this->cmsIconButton('Delete Item',$this->imgUrl . '/icon_del.png',$linkDelete);
										
											$strIconButton	= $btnInfo . ' ' . $btnDelete;
											
											$cid			= $this->formCheckbox('cid[]',$val['id']);
									?>
                                    <tr class="even">						
                                        <td align="center"><?php echo $cid;?></td>
                                        <td align="left"><?php echo $browser;?></td>
                                        <td align="center"><?php echo $ip;?></td>
                                        <td align="center"><?php echo $status;?></td>                                        
                                        <td align="center"><?php echo $timelogin;?></td>
                                        <td align="center"><?php echo $username;?></td>                                        
                                        <td align="center"><?php echo $strIconButton;?></td>
                                        <td align="center"><?php echo $id;?></td>
                                    </tr>
                                    <?php 
										}
										
                                    ?>
                                    <!-- BEGIN: PAGINATION (FOOT) -->
                                    <tfoot>
                                        <tr>
                                            <td colspan="9">
                                                <div class="container">
                                                    <div class="pagination">
                                                        <?php 
                                                        	$currentUrl = $this->baseUrl($this->currentController . '/index');
                                                        	echo $this->paginationControl($this->panigator,'Sliding','pagination.phtml',array('currentUrl'=>$currentUrl));
                                                        	
                                                        	// display items per page
                                                        	$linkSlbPagging = $this->baseUrl($this->currentController . '/filter/type/pagging');
                                                        	$options = array(5=>'5',
                                                        					10=>'10',
                                                        					20=>'20',
                                                        					30=>'30',
                                                        					50=>'50',
                                                        					100=>'100',
                                                        					200=>'200');
                                                        	if($ssFilter['pagging']=='')
                                                        		$ssFilter['pagging']=20;
															$numPerPage = $this->formSelect('pagging',$ssFilter['pagging'],
																							array('onchange'=>"OnSubmitForm('" . $linkSlbPagging . "')"),
																							$options);
															echo 'Items per page:'.$numPerPage;
                                                        ?>
                                                        <div class="limit"></div>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>					
                                    </tfoot>				<!-- END: PAGINATION (FOOT) -->
                                </table>
                                <!-- Area 4: In du lieu lay tu database - End -->

                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>