<?php
	
?>

<div data-role="page" class="jqm-demos ui-responsive-panel" id="panel-fixed-thoitiet">

    <div data-role="header" data-theme="c" >
        <h1>Tỷ giá</h1>
        <?php echo $this->showCategory($this);?>
        <a href="<?php echo $this->baseUrl('');?>" data-icon="home" data-iconpos="notext" data-transition="slide">Home</a>
    </div><!-- /header -->

    <div data-role="content" class="jqm-content">
		<!--div id="tigia-usd-content">
        <?php echo $this->tigiaUSD;?>
        </div-->
        
	    <div id="tigia-content">
            <div id="tigia-vang">
                <div id="vang-left">
                    <h2>Vàng trong nước</h2>
                    <div id="vang-left-content"><img src="<?php echo $this->baseUrl('public/templates/public/online/images/loading.gif') ?>" /></div>
                </div>
                <div id="vang-right">
                    <h2>Vàng quốc tế</h2>
                    <div id="vang-right-content"><img src="<?php echo $this->baseUrl('public/templates/public/online/images/loading.gif') ?>" /></div>
                </div>
            </div>
            
            <div id="bieudo-vang">
                <div id="bieudo-left">
                    <h2>Biểu đồ vàng trong nước</h2>
                    <div id="bieudo-left-content"><img src="<?php echo $this->baseUrl('public/templates/public/online/images/loading.gif') ?>" /></div>
                </div>
                <div id="bieudo-right">
                    <h2>Biểu đồ vàng quốc tế</h2>
                    <div id="bieudo-right-content"><img src="<?php echo $this->baseUrl('public/templates/public/online/images/loading.gif') ?>" /></div>
                </div>
            </div>
            <div style="float: right; padding-top:10px; padding-left:4px;"><strong>Nguồn: </strong> <a href="http://www.eximbank.com.vn/" target="_blank">Ngân hàng Eximbank</a></div>
        </div>
        <script>
            $(document).ready(function() 
            {
               
                $.ajax({
                      type: 'POST',
                      url:'<?php $this->baseUrl();?>service/tigia/getvang',
                      data: {},
                      dataType:'json',
                      success:function(data){ 
                        if(parseInt(data.rs) == 1)
                        {
                            //alert(data.bieudotrongnuoc);
                            $('#vang-left-content').html((data.vangtrongnuoc));
                            $('#vang-right-content').html((data.vangquocte));
                            $('#bieudo-left-content').html('<img width="290" height="227" src="' + data.bieudotrongnuoc + '" />');
                            $('#bieudo-right-content').html('<img  width="292px" height="229" src="' + data.bieudoquocte + '" />');
                            $('#chanel-content table').attr('cellpadding','0');
                            $('table.exchange').attr('cellspacing','0');
                            $('table.exchange').attr('border','0');
                            $('table.exchange').addClass('ta1');
                            $('table.exchange th').addClass('pt_title');
                            $('table.exchange tr:even').addClass('pt_mau2');
                            $('table.exchange tr:eq(0)').css('font-weight','bold');
                            return false;            
                        }
                      }      
                    });
                
            });
        </script>
        <!--//Giá vàng-->
		
    </div><!-- /content -->

	
	<?php echo $this->showCategory($this,'service');?>
	
</div><!-- /page -->
