<div id="category">
    <div class="wrapper">
        <div id="cat-content">
            <div id="cat-left">
                <div id="category-detail">
                    <div id="chanel-box">
                        <div class="nav_link">
                            <h2><span style="float: left;margin-right: 5px;"><a href="<?php echo DOMAIN_NAME; ?>" title="">TRANG CHỦ</a></span> <span style="float: left;margin-right: 6px; margin-top:1px"><img src="<?php echo DOMAIN_NAME;?>public/templates/public/online/images/breadcrumb-right.png" /></span> <span style="float: left;">Tỉ giá vàng</span></h2>
                        </div>
                        <div class="category-detail">
                            <div class="clr">
                                <div class="xoso-title" style="float: left;">XEM TỈ GIÁ VÀNG</div>
                                <div style="float: right; padding-top:10px; padding-left:4px;"><strong>Nguồn: </strong> <a href="http://sacombank-sbj.com/kinh-doanh-vang/35-h-1.aspx" target="_blank">Ngân hàng Sacombank</a></div>
                                
                            </div>
                            <div class="clr"></div>
                            <div id="tigia-content">
                                <div id="tigia-vang">
                                    <div id="vang-left">
                                        <h2>Tỉ giá vàng trong nước</h2>
                                        <div id="vang-left-content"><img src="<?php echo $this->baseUrl('public/templates/public/online/images/loading.gif') ?>" /></div>
                                    </div>
                                    <div id="vang-right">
                                        <h2>Tỉ giá vàng quốc tế</h2>
                                        <div id="vang-right-content"><img src="<?php echo $this->baseUrl('public/templates/public/online/images/loading.gif') ?>" /></div>
                                    </div>
                                </div>
                                
                                <div id="bieudo-vang">
                                    <div id="bieudo-left">
                                        <h2>Biểu đồ vàng trong nước</h2>
                                        <div id="bieudo-left-content"><img src="<?php echo $this->baseUrl('public/templates/public/online/images/loading.gif') ?>" /></div>
                                    </div>
                                    <div id="bieudo-right">
                                        <h2>Biểu đồ vàng quốc tế</h2>
                                        <div id="bieudo-right-content"><img src="<?php echo $this->baseUrl('public/templates/public/online/images/loading.gif') ?>" /></div>
                                    </div>
                                </div>
                            </div>
                            <script>
                                $(document).ready(function() 
                                {
                                    getContentTigia();
                                });
                            </script>
                        </div>
                    </div>
                </div>
            </div>
            <div id="cat-right">
                <?php $this->ShowMenuRight($this);?>
                <?php $this->ShowTinTigia($this);?>
                <?php $this->ShowCopyRight($this);?>
            </div>
        </div>
    </div>
</div>