<div align="center">
<?

    if(isset($this->errorMessage)){

                echo $this->errorMessage;

    }?>
    <style>
        a.openid{display: inline-block !important;
        height: 22px !important;
        width: 150px !important;}
    </style>
    
    <a class="openid" href="<?=$this->url(array('module'=>'oauth','controller'=>'user','action'=>'login'))."?openid_identifier=https://www.google.com/accounts/o8/id"?>" style="background: url('http://www.themuasam.vn/public/templates/public/themuasam/images/oauth/google_signin.png') repeat scroll 0 0 transparent !important;"></a>
    <a class="openid" href="<?=$this->url(array('module'=>'oauth','controller'=>'user','action'=>'login'))."?openid_identifier=https://www.facebook.com"?>" style="background: url('http://www.themuasam.vn/public/templates/public/themuasam/images/oauth/facebook_signin.png') repeat scroll 0 0 transparent !important;"></a>
    <a class="openid" href="<?=$this->url(array('module'=>'oauth','controller'=>'user','action'=>'login'))."?openid_identifier=http://me.yahoo.com/"?>" style="background: url('http://www.themuasam.vn/public/templates/public/themuasam/images/oauth/yahoo_signin.png') repeat scroll 0 0 transparent !important;"></a>

    <?

                echo $this->form;

    ?>

    <a href="<?=$this->url(array('controller'=>'user','action'=>'signup'))?>">New users click here?</a>
</div>

