<?php

//$dir=$this->arrParam['controllerConfig']['Dir'];

if(count($this->items))
{


    $html='';
    foreach ($this->items as $key => $value) {


        
        switch ($value['file_type']) {
            case 'image':
                $imageLink=PUBLIC_URL.'/files/media/'.$value['folder']. $value['name'];
                break;
            
            default:
                $imageLink=$this->imgUrl.'/thumbs/'.$this->arrImageDefault[$value['file_type']];
                
                break;
        }

        
        $html.='
        <li class="blockitem">
            <a href="ajax/image.html" data-rel="image"><img src="'.$imageLink.'" alt="" /></a>
            <span class="filename">'.$value['name'].'</span>
        </li> 
        ';
    }

    
}
?>

<ul class="listfile">

<?php echo $html;?>
</ul>
<?php 

    $currentUrl = $this->baseUrl($this->currentController . '/index');
    echo $this->paginationControl($this->panigator,'Sliding','pagination.phtml',array('currentUrl'=>$currentUrl));
    
    // display items per page
    $linkSlbPagging = $this->baseUrl($this->currentController . '/filter/type/pagging');
    $options = array(5=>'5',
                    10=>'10',
                    20=>'20',
                    30=>'30',
                    50=>'50',
                    100=>'100',
                    200=>'200');
    if($ssFilter['pagging']=='')
        $ssFilter['pagging']=20;
    $numPerPage = $this->formSelect('pagging',$ssFilter['pagging'],
                                    array('onchange'=>"OnSubmitForm('" . $linkSlbPagging . "')"),
                                    $options);
    echo 'Items per page:'.$numPerPage;
?>

