<?php
/*echo 'This is view of Paginator';
echo $this->currentUrl;*/

	$linkStart 		= $this->currentUrl . '/page/' . $this->first;
	
	$linkPrevious = '#';
	if(isset($this->previous)){
		$linkPrevious 	= $this->currentUrl . '/page/' . $this->previous;
	}
	$linkNext = '#';
	if(isset($this->next)){
		$linkNext 		= $this->currentUrl . '/page/' . $this->next;
	}
	
	$linkEnd 		= $this->currentUrl . '/page/' . $this->last;
	
	$arrPage=array();
	$strPage  = '';
	foreach ($this->pagesInRange as $key){
		$arrPage[]= $key;
		if($this->current == $key){
			//$strPage .= '<span>' . $key .'</span>';
			$strPage.='<li class="active"><a href="#">' . $key .'</a></li>';
		}else{
			$linkPage = $this->currentUrl . '/page/' . $key;
			//$strPage .= '<a href="' . $linkPage . '">' . $key .'</a>'; 
			$strPage.='<li><a href="' . $linkPage . '">' . $key .'</a></li>';
		}
	}

	$page = 'Page ' . $this->current .' Of ' . $this->last;
?>




<div class="pagination">
    <ul>
    	<?php if(!in_array($this->first,$arrPage)){ ?>
	    <li><a href="<?php echo $linkStart;?>">Trang đầu</a></li>
	    <?php }?>

	    <?php if(!in_array($this->first,$arrPage)){ ?>
	    <li><a href="<?php echo $linkPrevious;?>" class="btn prev prev_disabled"><span class="icon-chevron-left"></span></a></li>
	    <?php }?>

	    <?php echo $strPage;?>
	    <?php if(!in_array($this->last,$arrPage)){ ?>
    	<li><a href="<?php echo $linkNext;?>" class="btn next next_disabled"><span class="icon-chevron-right"></span></a></li>
    	<?php }?>
    	<?php if(!in_array($this->last,$arrPage)){ ?>
    	<li><a href="<?php echo $linkEnd;?>">Trang cuối</a></li>
    	<?php }?>
    </ul>
</div>
