<?php 
$userInfo=$this->infoUser['member'];
$groupInfo=$this->infoUser['group'];


$avatar='';

if(!$userInfo['avatar'])
{
    $avatar=$this->imgUrl.'/profilethumb.png';
}
else
{
    $avatar=$userInfo['avatar'];
}

?>

<div class="mainwrapper">
	
    <!-- START OF LEFT PANEL -->
    <div class="leftpanel">
    	<?php $this->adminMenu($this);?>
    </div><!--mainleft-->
    <!-- END OF LEFT PANEL -->
    
    <!-- START OF RIGHT PANEL -->
    <div class="rightpanel">
    	<?php $this->adminHeaderpanel($this);?>
    	<?php $this->adminBreadcrumbwidget($this);?>


        <div class="pagetitle">
            <h1>Edit Profile</h1> <span>This is a sample description for edit profile page...</span>
        </div><!--pagetitle-->
        
        <div class="maincontent">
            <div class="contentinner content-editprofile">
                <h4 class="widgettitle nomargin">Edit Profile</h4>
                <div class="widgetcontent bordered">
                    <div class="row-fluid">
                        <div class="span3 profile-left">
                        
                            <h4>Your Profile Photo</h4>
                            
                            <div class="profilethumb">
                                <a href="">Change Thumbnail</a>
                                <img src="<?php echo $avatar;?>" alt="" class="img-polaroid" />
                            </div><!--profilethumb-->
                            
                            
                            <!--h4>Tags</h4>
                            
                            <ul class="taglist">
                                <li><a href="">HTML5 <span class="icon-remove"></span></a></li>
                                <li><a href="">CSS <span class="icon-remove"></span></a></li>
                                <li><a href="">PHP <span class="icon-remove"></span></a></li>
                                <li><a href="">jQuery <span class="icon-remove"></span></a></li>
                                <li><a href="">Java <span class="icon-remove"></span></a></li>
                                <li><a href="">GWT <span class="icon-remove"></span></a></li>
                                <li><a href="">CodeNgniter <span class="icon-remove"></span></a></li>
                                <li><a href="">Bootstrap <span class="icon-remove"></span></a></li>
                            </ul>
                            <a href="" style="display:block;margin-top:10px">+ Add Tag</a-->
                            
                        </div><!--span3-->
                        <div class="span9">
                            <form action="editprofile.html" class="editprofileform" method="post">
                                <h4>Login Information</h4>                               
                                <p>
                                    <label>Email:</label>
                                    <input type="text" name="email" class="input-xlarge" value="<?php echo $userInfo['email'];?>" />
                                </p>
                                <p>
                                    <label style="padding:0">Old Password</label>
                                    <input type="password" name="password" class="input-xlarge" value="" />
                                </p>
                                <p>
                                    <label style="padding:0">New Password</label>
                                    <input type="new_password" name="new_password" class="input-xlarge" value="" />
                                </p>
                                <p>
                                    <label style="padding:0">Confirm Pass</label>
                                    <input type="confirm_password" name="confirm_password" class="input-xlarge" value="" />
                                </p>
                                <br />
                                
                                <h4>Personal Information</h4>
                                <p>
                                    <label>Firstname:</label>
                                    <input type="text" name="firstname" class="input-xlarge" value="Theme" />
                                </p>
                                <p>
                                    <label>Lastname:</label>
                                    <input type="text" name="lastname" class="input-xlarge" value="Pixels" />
                                </p>
                                <p>
                                    <label>Location:</label>
                                    <input type="text" name="location" class="input-xlarge" value="Cebu, Philippines" />
                                </p>
                                <p>
                                    <label>Your Website:</label>
                                    <input type="text" name="website" class="input-xlarge" value="http://themepixels.com/" />
                                </p>
                                <p>
                                    <label>About You:</label>
                                    <textarea name="about" class="span8"></textarea>
                                </p>
                                
                                <br />
                                
                                <h4>Notifications</h4>
                                <p>
                                    <input type="checkbox" /> Email me when someone mentions me... <br />
                                    <input type="checkbox" /> Email me when someone follows me...
                                </p>
                                
                                <br />
                                <p>
                                    <button type="submit" class="btn btn-primary">Update Profile</button> &nbsp; <a href="">Deactivate your account</a>
                                </p>
                            </form>
                        </div><!--span9-->
                    </div><!--row-fluid-->
                </div><!--widgetcontent-->
            </div><!--contentinner-->
        </div><!--maincontent-->
        
    </div><!--mainright-->
    <!-- END OF RIGHT PANEL -->
    
    <div class="clearfix"></div>
    
    <div class="footer">
        <div class="footerleft">Katniss Premium Admin Template v1.0</div>
        <div class="footerright">&copy; ThemePixels - <a href="http://twitter.com/themepixels">Follow me on Twitter</a> - <a href="http://dribbble.com/themepixels">Follow me on Dribbble</a></div>
    </div><!--footer-->

    
</div><!--mainwrapper-->
<script type="text/javascript">
jQuery(document).ready(function(){

    jQuery('.profilethumb').hover(function(){
        jQuery(this).find('a').fadeIn();
    },function(){
        jQuery(this).find('a').fadeOut();
    });
    
    jQuery('.taglist a').click(function(){
        return false;
    });
    jQuery('.taglist a span').click(function(){
        jQuery(this).parent().remove();
        return false;
    });
    
});
</script>