<?php 

$userInfo=$this->userInfo;




$detail=$this->detail;
$infoNext=$this->infoNext;
$infoPrev=$this->infoPrev;


$title=$detail['title'];



$rw=new Zendvn_View_Helper_CmsRewriteLink();

$info['title']=$rw->noSign(trim($title));
$info['id']=$detail['id'];
if($info['id'] && $info['title'])
    $linkDetail   = $this->serverUrl($this->url($info,'article-index-detail'));


if($infoNext)
{

    if($infoNext['id'] && $infoNext['title'])
        $strLinkNext=$this->serverUrl($this->url(array('title'=>$rw->noSign(trim($infoNext['title'])),'id'=>$infoNext['id'])));
    $linkNext = '<a id="prev_post" class="prev-post" href="'.$strLinkNext.'">Bài trước</a>';
}
if($infoPrev)
{


    if($infoPrev['id'] && $infoPrev['title'])
        $strLinkPrev=$this->serverUrl($this->url(array('title'=>$rw->noSign(trim($infoPrev['title'])),'id'=>$infoPrev['id'])));
    $linkPrev = '<a id="next_post" class="next-post" href="'. $strLinkPrev.'">Bài sau</a>';
}

$content='';
switch ($detail['type']) {
    case 'image':
        
        $image=PUBLIC_URL.'/files/article/images/'.$detail['image'];
        $content='<div class="img-wrap" itemtype="http://schema.org/ImageObject" itemscope="">
            <img itemprop="contentURL" alt="'.$title.'" src="'.$image.'">
            </div>';
        break;
    case 'video':
        $image=$detail['image'];
        $video=$detail['video'];
        $content='
        <div class="img-wrap" itemscope="" itemid="" itemtype="http://schema.org/VideoObject">
        <link itemprop="url" href="'.$linkDetail.'">
        <meta itemprop="name" content="'.$title.'">
        <meta itemprop="description" content="">
        <meta itemprop="paid" content="False">
        <meta itemprop="duration" content="PT2M6S">
        <meta itemprop="unlisted" content="False">
        <link itemprop="thumbnailUrl" href="'.$image.'">
        <span itemprop="thumbnail" itemscope="" itemtype="http://schema.org/ImageObject">
          <link itemprop="url" href="'.$image.'">
          <meta itemprop="width" content="320">
          <meta itemprop="height" content="180">
        </span>
        <link itemprop="embedURL" href="'.$video.'?feature=oembed&amp;&amp;wmode=opaque&amp;rel=0&amp;showinfo=0&amp;modestbranding=1&amp;version=3&amp;ps=docs&amp;nologo=1&amp;theme=light&amp;color=white&amp;iv_load_policy=0&amp;cc_load_policy=1">
        <meta itemprop="playerType" content="Flash">
        <meta itemprop="width" content="700">
        <meta itemprop="height" content="394">
        <meta itemprop="isFamilyFriendly" content="True">
        <meta itemprop="regionsAllowed" content="AD,AE,AF,AG,AI,AL,AM,AO,AQ,AR,AS,AT,AU,AW,AX,AZ,BA,BB,BD,BE,BF,BG,BH,BI,BJ,BL,BM,BN,BO,BQ,BR,BS,BT,BV,BW,BY,BZ,CA,CC,CD,CF,CG,CH,CI,CK,CL,CM,CN,CO,CR,CU,CV,CW,CX,CY,CZ,DE,DJ,DK,DM,DO,DZ,EC,EE,EG,EH,ER,ES,ET,FI,FJ,FK,FM,FO,FR,GA,GB,GD,GE,GF,GG,GH,GI,GL,GM,GN,GP,GQ,GR,GS,GT,GU,GW,GY,HK,HM,HN,HR,HT,HU,ID,IE,IL,IM,IN,IO,IQ,IR,IS,IT,JE,JM,JO,JP,KE,KG,KH,KI,KM,KN,KP,KR,KW,KY,KZ,LA,LB,LC,LI,LK,LR,LS,LT,LU,LV,LY,MA,MC,MD,ME,MF,MG,MH,MK,ML,MM,MN,MO,MP,MQ,MR,MS,MT,MU,MV,MW,MX,MY,MZ,NA,NC,NE,NF,NG,NI,NL,NO,NP,NR,NU,NZ,OM,PA,PE,PF,PG,PH,PK,PL,PM,PN,PR,PS,PT,PW,PY,QA,RE,RO,RS,RU,RW,SA,SB,SC,SD,SE,SG,SH,SI,SJ,SK,SL,SM,SN,SO,SR,SS,ST,SV,SX,SY,SZ,TC,TD,TF,TG,TH,TJ,TK,TL,TM,TN,TO,TR,TT,TV,TW,TZ,UA,UG,UM,US,UY,UZ,VA,VC,VE,VG,VI,VN,VU,WF,WS,YE,YT,ZA,ZM,ZW">
        <center>
        <iframe width="700" height="394" frameborder="0" allowfullscreen="" src="'.$video.'?feature=oembed&amp;modestbranding=1&amp;version=3&amp;ps=docs&amp;nologo=1&amp;theme=light&amp;color=white&amp;iv_load_policy=0&amp;cc_load_policy=1">
        </iframe>
        </center>    
    </div>
        ';
        break;
    default:
        $content=$detail['description'];
        break;
}




$arrOrder=$this->listOrder;
$contentOrder='';
$k=0;
for($i=1;$i<=2;$i++)
{
    for($j=1;$j<=3;$j++)
    {

        $item=$arrOrder[$k];
        if(!$item)
            break;
       
        $info['title']=$rw->noSign(trim($item['title']));
        $info['id']=$item['id'];
        if($info['id'] && $info['title'])
            $linkDetailOrderItem   = $this->serverUrl($this->url($info,'article-index-detail'));

        switch ($item['type']) {
            case 'image':
                $imageOrder=PUBLIC_URL.'/files/article/images/'.$item['image'];
                break;    
            case 'video':
                $imageOrder=$item['image'];
                break;
        }
        

        $contentOrder.='<ul id="grid-col-'.$i.'" class="col-'.$j.'">
                <li class=" ">
                    <a href="'.$linkDetailOrderItem.'" class="jump_stop">
                        <div style="" class="thimage">
                        <img src="'.$imageOrder.'" alt="'.$item['title'].'">
                       </div>
                    </a>
                    <h1>'.$item['title'].'</h1>
                </li>
            </ul>';
        $k++;    
    }                                        
}



?>

<div id="wrapper">
        <div id="content">
            <div id="content-left">
                <div id="left-content">
                    <!--content left start-->
                    <div class="post-info-pad">
                        <h1><?php echo $title;?></h1>
                        <p>
                            <span id="view_count" class="view" votes="164" score="0" title="Lượt xem">Lượt xem: <b><?php echo $detail['view_count'];?></b></span>
                            <span id="like_count" class="like_count" votes="4" score="0" title="Like">Like: <b><?php echo $detail['like_count'];?></b></span> 
                            <span id="view_comment" class="view_comment" title="Bình luận">Bình luận: <b><?php echo $detail['comment_count'];?></b></span>
                                                                                        
                        </p>
                        <p>
                            Nguồn:<b>&nbsp;Sưu tầm</b>
                                            </p>
                        
                        <div class="userinfo">
                            <a href="<?php //echo $userInfo['user_id'];?>"><img src="<?php echo $userInfo['avatar'];?>"></a>
                            <div class="uinfo">
                                <div>Đăng 4 giờ trước bởi</div>
                                <a href="<?php //echo $userInfo['user_id'];?>"><?php echo $userInfo['full_name'];?></a>
                            </div>
                            <div class="clear"> </div>
                        </div>
                         
                    </div>
                    <div class="clear"></div>
                    <div id="moving-like" style="position: static; top: 41px; z-index: 200;">
                        <div id="post-control-bar" class="spread-bar-wrap">
                            <div class="spread-bar"><span style="float: left; color: rgb(59, 89, 152); font-size: 13px; padding-top: 3px; padding-right: 10px;">Bạn thích bài này ?</span>
                                                    
                                 <?php echo $this->ShowFb(array('detail'=>$linkDetail),array('type'=>'like')); ?>
                                
                            </div>
                            <div class="post-next-prev">                                
                                <?php echo $linkNext;?>
                                <?php echo $linkPrev;?>
                            </div>
                        </div>
                    </div>
                    <div class="clear"></div>
                    <div class="content-article">
                        <div class="post-container">
                            <?php echo $content;?>  
                        </div>
                    </div>
                    <div class="clear"></div>
                    <div id="post-control-bar" class="spread-bar-wrap">
                        <div class="spread-bar post-ctr-bar">
                            <span>
                                <a style="font-size: 13px;padding-top:5px;padding-right:5px;float:left;color:#3B5998;" href="https://www.facebook.com/shockvl.shockdentanoc">Like Shockvl.com trên Facebook: </a>
                            </span>
                            <div style="float:left;" class="fb-like fb_edge_widget_with_comment fb_iframe_widget" data-href="<?php echo FANPAGE;?>" data-send="false" data-width="400" data-show-faces="false" fb-xfbml-state="rendered"></div>                    
                            <div class="clear"></div>
                        </div>   
                       
                    </div>
                    <div class="clear"></div>
                    <div class="comment-section">
                        <h3 class="title" id="comments">Bình luận</h3>
                        <span class="report-and-source">
                        <p>
                            <!--<a class="fix" href="http://www.ovui.vn/fix/17758">Chỉnh lại bài này</a>-->
                            <a id="report-item-link" class="report report-item" entryid="17758" href="javascript:void(0);">Báo xấu</a>                    </p>
                        </span>
                        <div style="margin-left:10px">                                                        
                            <?php echo $this->ShowFb(array('detail'=>$linkDetail),array('type'=>'comment')); ?>
                        </div>
                  
                    </div>
                    <div class="clear"></div>
                    <div class="post-may-like">
                        <h3 style="margin-left: 15px;margin-top: 10px;">Xem thêm các bài "Sốc"</h3>
                        <h3>
                            <div id="entries-content" class="grid">  
                                <?php

                                    echo $contentOrder;
                                ?>


                                
                            </div>
                        </h3>
                    </div>


                    <!--content left end-->
                </div>
            </div>

            <div id="content-right">
                <div id="side-bar">
                    <?php echo $this->ShowSidebar($this,'');?>
                </div>    
            </div>
        </div>
    </div>

    
