<?php 
$userInfo = $this->arrUserInfo;

$html='';

//$showFb = Block_ShowFb::_();



foreach ($this->listArticle as $key => $value) {

    $rw=new Zendvn_View_Helper_CmsRewriteLink();
    $info['title']=$rw->noSign(trim($value['title']));
    $info['id']=$value['id'];
    $linkDetail   = $this->serverUrl($this->url($info,'article-index-detail'));



    switch ($value['type']) {
        case 'image':
            $image=PUBLIC_URL.'/files/article/images/'.$value['image'];
            $contentWrap='
                <div class="img-wrap">
                    <a href="'.$linkDetail.'" target="_blank">
                        <img class="shockvl" src="'.$image.'" alt="'.$value['title'].'" />
                    </a>
                </div>
            ';
            break;
        case 'video':
            $image=$value['image'];
            $contentWrap='
                <div class="img-wrap">
                    <a href="'.$linkDetail.'" target="_blank">
                        <img class="shockvl" src="'.$image.'" alt="'.$value['title'].'" />
                        <img class="videoPlay" src="http://www.shockvl.com/public/templates/public/shockvl/images/button_play_red.png" alt="'.$value['title'].'" />
                    </a>
                </div>
            ';
            break;  
        
        default:
            # code...
            break;
    }


    $html.='



    <div class="row">
        <div class="large-12 columns">
            
            <div class="large-9 columns">
                '.$contentWrap.'
            </div>
            <div class="large-3 columns">
                <div class="info-entries">
                    <h1>
                        <a target="_blank" href="'.$linkDetail.'">'.$value['title'].'</a>
                    </h1>
                    <div class="uploader">Đăng bởi<a href="#">'.$userInfo[$value['user_id']]['full_name'].'</a> lúc '.$value['create_date'].'</div>
                    <div class="sharing-box">
                        <div class="sharing">
                            '. $this->ShowFb(array('detail'=>$linkDetail),array('type'=>'like')).'
                        </div>
                    </div>
                </div>
            
            </div>
        </div>          
    </div>

    ';

    
}
?>
<div class="row">
    <div class="large-9 columns">
        <?php echo $html;?>
    </div>
     <div class="large-3 columns">
        <div id="side-bar">
            <?php //echo $this->ShowSidebar($this,'');?>
        </div>
    </div>
</div>



<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1&appId=134121816783332";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


