<?php 
	if(!empty($this->errors)){
		$errors = $this->formErrors($this->errors);
	}
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">



                        <?php //echo $this->render('public/toolbar/index.php')?>
                        <div class="clr"></div>
                         <?php // echo $this->render('admin-user/sublink/index.php')?>

                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
						<div id="adminfieldset">
                             <div class="adminheader">Detail</div>
										
							<?php 
                         		if(!empty($this->errors)){
                         			
	                         			echo '<div id="errors">';
										echo '<pre>';
											print_r($errors);
										echo '</pre>';
										echo '</div>';
                         			
								}
                         		
								?>			
									
                         		
								
							
                                
							</div>
							
                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>