<div id="main-wrapper">
            <div class="clearfix" id="main">
                <div role="complementary" class="column sidebar" id="sidebar-second">
                    <div class="section">
                        <div class="region region-sidebar-second">
                            
                                <?php echo $this->partial('_partial/listCat.phtml',array('listCat'=>$this->listCat));?>
                                <?php // echo $this->partial('_partial/latestNews.phtml',array('items'=>$this->latestNews));?>
               					                             
                        </div>
                    </div><!-- /.section -->
                </div><!-- /#sidebar-second -->
                <div role="main" class="column" id="content">
                    <div class="section">
                        <!--h1 id="page-title" class="title">Blogs</h1-->
      					 <?php echo $this->Showpath($this);?>
                        <br class="clear" />
                        <div class="tabs"></div>
                        <div class="region region-content">
                            <div class="block block-system block-odd" id="block-system-main">
                                <div class="content">
                                  <?php 
										echo $this->partial('_partial/newsItem.phtml',array('items'=>$this->listAlbum));										
										echo $this->paginationControl($this->panigator,'Sliding','_partial/paging.phtml',array('currentUrl'=>$this->currentUrl));
									?>
                                </div>  
                            </div><!-- /.content -->
                        </div><!-- /.block -->
                    </div>
                </div><!-- /.section -->
            </div><!-- /#content -->
        </div><!-- /#main -->





<?php 
$item	=	$this->item;
?>

<div id="warrap_news_detail">
<div id="content_secsion">
<!-- Content -->
<section class="padcontent2">
	<div class="container_12">
		<div class="wrapper">
			<div class="grid_8">
		<?php echo $this->Showpath($this);	?>
            <div class="clear"></div>
				<div class="wrapper indent">
                <div id="news_detail">
					  <h1 class="news_title"><?php echo $this->cmsConvertDbToView($item['title']);?></h1>
                  <h2 class="news_description"><?php echo $this->cmsConvertDbToView($item['summary']);?></h2>
                  <div class="news_content">
                    <?php echo $this->cmsConvertDbToView($item['content']);?>
                  </div>
                </div>
				</div>
			</div>
			<div class="grid_4">
				<?php echo $this->partial('_partial/listCat.phtml',array('listCat'=>$this->listCat));?>
              <div class="padline3"><div class="lineH"></div></div>
                <?php echo $this->partial('_partial/latestNews.phtml');?>
            </div>
		</div>
	</div>
</section>
</div>
</div>