<script type="text/javascript">
	$(document).ready(function(){
		$('.box-img a').fancybox({
			'titlePosition' : 'over'
		}); 
	});
</script>
<style>
	#fancybox-title-over,#fancybox-title-over p{color:#FFFFFF}
</style>
<div id="warrap_news">
                <div id="content_secsion">
                    <!-- Content -->
                	<section class="padcontent2">
                		<div class="container_12">
                			<div class="wrapper">
                				<div class="grid_8">
									<?php echo $this->Showpath($this);	?>
                                    <div class="clear"></div>
                					<div class="wrapper indent">
									<?php 
										echo $this->partial('_partial/photoView.phtml',array('items'=>$this->items));										
										echo $this->paginationControl($this->panigator,'Sliding','_partial/paging.phtml',array('currentUrl'=>$this->currentUrl));
									?>
									
									</div>
                				</div>
                				<div class="grid_4">

									<?php echo $this->partial('_partial/listCat.phtml',array('listCat'=>$this->listCat));?>
		

                					<div class="padline3"><div class="lineH"></div></div>
                                  	<?php echo $this->partial('_partial/latestNews.phtml',array('items'=>$this->latestNews));?>
                                    <!--Quang cao-->
                                    <?php $this->ShowADSByModuleAndPosition('right',$this->arrParam['module'],$this,NULL);?>
                				</div>
                			</div>
                		</div>
                	</section>
                </div>
</div>
