<?php 

	
	$old_password 		= $this->formPassword('old_password','',array('class'=>'txtmedium'));
	$new_password 		= $this->formPassword('new_password','',array('class'=>'txtmedium'));
	$re_new_password 		= $this->formPassword('re_new_password','',array('class'=>'txtmedium'));
	
	if(!empty($this->errors)){
		$errors = $this->formErrors($this->errors );
	}
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">



                        <?php echo $this->render('public/toolbar/index.php')?>
                        <div class="clr"></div>
                         <?php echo $this->render('public/sublink/index1.php')?>

                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
						<div id="adminfieldset">
                             <div class="adminheader">Password</div>
										
                         		<?php 
                         		if(!empty($this->errors)){
                         			if($this->errors[0]=="success"){
                         				echo '<div id="success">';
										echo '<pre>';
											print_r($errors);
										echo '</pre>';
										echo '</div>';
                         				
                         			}
                         			else{
	                         			echo '<div id="errors">';
										echo '<pre>';
											print_r($errors);
										echo '</pre>';
										echo '</div>';
                         			}
								}
                         		
								?>
								
								
                                <div id="row">
                                    <div class="label">Current Password:</div>
                                    <?php echo $old_password;?>			
                                </div>
                                <div class="clr"></div>
                                <div id="row">
                                    <div class="label">New Password:</div>
                                    <?php echo $new_password;?>			
                                </div>
                                <div class="clr"></div>
                                <div id="row">
                                    <div class="label">Retype New Password:</div>
                                    <?php echo $re_new_password;?>			
                                </div>
                                <div class="clr"></div>
                               
                                
							</div>
							
                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>