<?php 

	$name 		= $this->formText('name',$this->Item['name'],array('class'=>'txtmedium'));
	//list Category select
	$option = $this->listCat;    
	unset($option[$this->Item['id']]);  
	foreach ($option as $key=>$value) 
		if($value['id']==$this->Item['id']) 
			  unset($option[$key]);   
    $listCat = $this->cmsCategorySelect('parents',$this->Item['parents'],$option,array('style'=>'width:255px'));
	
	
	//$parent_name= $this->Item['parent_name'];
	$order		= $this->formText('order',$this->Item['order'],array('class'=>'txtmedium'));
	$options 		= array('Inactive','Active');
	$status 		= $this->formRadio('status',$this->Item['status'],null,$options, ' ');
	
	if(!empty($this->errors)){
		$errors = $this->formErrors($this->errors );
	}
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">



                        <?php echo $this->render('admin-product-location/toolbar/index.php')?>
                        <div class="clr"></div>
                         <?php echo $this->render('admin-product-location/sublink/index.php')?>

                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
						<div id="adminfieldset">
                             <div class="adminheader">Detail</div>
										
                         		<?php 
                         		if(!empty($this->errors)){
                         			if($this->errors[0]=="success"){
                         				echo '<div id="success">';
										echo '<pre>';
											print_r($errors);
										echo '</pre>';
										echo '</div>';
                         				
                         			}
                         			else{
	                         			echo '<div id="errors">';
										echo '<pre>';
											print_r($errors);
										echo '</pre>';
										echo '</div>';
                         			}
								}
                         		
								?>
								
								<div id="row">
                                    <div class="label">Location name:</div>
                                    <?php echo $name;?>			
                                </div>
                                <div class="clr"></div>
                                <div id="row">
                                    <div class="label">Location parent:</div>
                                    <?php echo $listCat;?>			
                                </div>
                                <div class="clr"></div>
                                <div id="row">
                                    <div class="label">Order:</div>
                                    <?php echo $order;?>			
                                </div>
                                <div class="clr"></div>
                                <div id="row">
                                    <div class="label">Status:</div>
                                    <?php echo $status;?>			
                                </div>
                                <div class="clr"></div>
                                
							</div>
							
                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>