<?php 

	$user_name 		= $this->formText('user_name',$this->Item['user_name'],array('class'=>'txtmedium'));
	$password 		= $this->formPassword('password',$this->Item['password'],array('class'=>'txtmedium'));
	$user_avatar	= $this->formFile('user_avatar',array('style'=>'width: 250px'));
	$email			= $this->formText('email',$this->Item['email'],array('class'=>'txtmedium'));
	
	$first_name 	= $this->formText('first_name',$this->Item['first_name'],array('class'=>'txtmedium'));
	$last_name 		= $this->formText('last_name',$this->Item['last_name'],array('class'=>'txtmedium'));
	
	$birthday		= $this->cmsDatepicker('birthday',$this->Item['birthday'],array('class'=>'txtmedium'), $this,'birthday');
	$options 		= array('Inactive','Active');
	$status 		= $this->formRadio('status',$this->Item['status'],null,$options, ' ');

	$options = $this->slbGroup;
	$slbGroup = $this->formSelect('group_id',$this->Item['group_id'],null,$options);
	
	$sign			= $this->cmsEditor('sign',$this->cmsConvertDbToView($this->Item['sign']),$width = '100%',$height = 500);
	if(!empty($this->errors)){
		$errors = $this->formErrors($this->errors );
	}
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data" >



                        <?php echo $this->render('admin-user/toolbar/index.php')?>
                        <div class="clr"></div>
                         <?php echo $this->render('admin-user/sublink/index.php')?>

                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
						<div id="adminfieldset">
                             <div class="adminheader">Detail</div>
										
                         		<?php 
                         		if(!empty($this->errors)){
                         			if($this->errors[0]=="success"){
                         				echo '<div id="success">';
										echo '<pre>';
											print_r($errors);
										echo '</pre>';
										echo '</div>';
                         				
                         			}
                         			else{
	                         			echo '<div id="errors">';
										echo '<pre>';
											print_r($errors);
										echo '</pre>';
										echo '</div>';
                         			}
								}
                         		
								?>
								
								<div id="row">
                                    <div class="label">User name:</div>
                                    <?php echo $user_name;?>			
                                </div>
                                <div class="clr"></div>
                                <div id="row">
                                    <div class="label">Password:</div>
                                    <?php echo $password;?>			
                                </div>
                                <div class="clr"></div>
                                <div id="row">
                                    <div class="label">Avatar:</div>
                                    <?php echo $user_avatar;?>			
                                </div>
                                <div class="clr"></div>
                                
                                <div id="row">
                                    <div class="label">Email:</div>
                                    <?php echo $email;?>			
                                </div>
                                <div class="clr"></div>
                                
                                <div id="row">
                                    <div class="label">First name:</div>
                                    <?php echo $first_name;?>			
                                </div>
                                <div class="clr"></div>
                                
                                <div id="row">
                                    <div class="label">Last name:</div>
                                    <?php echo $last_name;?>			
                                </div>
                                <div class="clr"></div>
                                
                                <div id="row">
                                    <div class="label">Birthday:</div>
                                    <?php echo $birthday;?>			
                                </div>
                                <div class="clr"></div>
                               
                                <div id="row">
                                    <div class="label">Status:</div>
                                    <?php echo $status;?>			
                                </div>
                                <div class="clr"></div>
                                <div id="row">
                                    <div class="label">Group:</div>
                                    <?php echo $slbGroup;?>			
                                </div>
                                <div class="clr"></div>
                                
                                <div id="row">
                                    <div class="label">Sign:</div>
                                    <?php echo $sign;?>			
                                </div>
                                <div class="clr"></div>
                                
							</div>
							
                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>