<?php
$ssFilter = $this->arrParam['ssFilter'];
?>
<form name="appForm" method="post" action="">



                        <?php echo $this->render('admin-product-order/toolbar/index.php')?>
                        <div class="clr"></div>
                         <?php echo $this->render('admin-product-order/sublink/index.php')?>

                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
								<div id="filters">
									<div>
										<?php echo "";?>
									</div>
								</div>	

                                <!-- Area 4: In du lieu lay tu database -->
                                <table class="adminlist">
                                    <thead>
                                        <tr>
                                            <th width="43" >
                                            	<input type="checkbox" name="checkbox" id="checkbox" onclick="checkedAll()">
                                           	</th>
                                            <th>Họ tên</th>
                                            <th width="250">Email</th>
                                            <th width="100">Phone</th>
                                            
                                            <th width="150">Ngày Order</th>
                                            <th width="89">Trạng thái</th>                                            
                                                                                   
                                            <th width="90">Control</th>
                                            <th width="34">ID</th>
                                        </tr>
                                    </thead>
									<?php 
										foreach($this->Items as $key => $val){
										//'id','name','phone','email','created','created_by','status'
                                        	$id 			= $val['id'];
											$name 			= $val['name'];
					                        $phone 			= $val['phone'];
											$email 			= $val['email'];
                                            $created 			= $val['created'];
                                            
											
											$status 		= $val['status'];
											if($status == 1){	
												$linkStatus = $this->baseUrl($this->currentController . '/status/type/0/id/' . $id);											
												$status = $this->cmsIconButton('Active', $this->imgUrl . '/icon/active.png',$linkStatus);
											}else{
												$linkStatus = $this->baseUrl($this->currentController . '/status/type/1/id/' . $id);
												$status = $this->cmsIconButton('INactive', $this->imgUrl . '/icon/inactive.png',$linkStatus);
											}
											
											
											
										
											
											$linkInfo		= $this->baseUrl($this->currentController . '/info/id/' . $id);											
											$btnInfo		= $this->cmsIconButton('View Item',$this->imgUrl . '/icon_info.png',$linkInfo);
											
											//$linkEdit		= $this->baseUrl($this->currentController . '/edit/id/' . $id);
											//$btnEdit		= $this->cmsIconButton('Edit Item',$this->imgUrl . '/icon_edit.png',$linkEdit);
											
											//$linkDelete		= $this->baseUrl($this->currentController . '/delete/id/' . $id);
											//$btnDelete		= $this->cmsIconButton('Delete Item',$this->imgUrl . '/icon_del.png',$linkDelete);
										
											$strIconButton	= $btnInfo . ' ' . $btnEdit . ' ' . $btnDelete;
											
											$cid			= $this->formCheckbox('cid[]',$val['id']);
									?>
                                    <tr class="even">						
                                        <td align="center"><?php echo $cid;?></td>
                                        <td align="left"><?php echo $name;?></td>
                                        <td align="left"><?php echo $email;?></td>
                                        <td align="left"><?php echo $phone;?></td>
                                        
                                        <td align="center"><?php echo $created;?></td>                                         
                                        <td align="center"><?php echo $status;?></td>                                        
                                        <td align="center"><?php echo $strIconButton;?></td>
                                        <td align="center"><?php echo $id;?></td>
                                    </tr>
                                    <?php 
										}
                                    ?>
                                    <!-- BEGIN: PAGINATION (FOOT) -->
                                    <tfoot>
                                        <tr>
                                            <td colspan="9">
                                                <div class="container">
                                                    <div class="pagination">
                                                        <?php 
                                                        	$currentUrl = $this->baseUrl($this->currentController . '/index');
                                                        	echo $this->paginationControl($this->panigator,'Sliding','pagination.phtml',array('currentUrl'=>$currentUrl));
                                                        	
                                                        	// display items per page
                                                        	$linkSlbPagging = $this->baseUrl($this->currentController . '/filter/type/pagging');
                                                        	$options = array(5=>'5',
                                                        					10=>'10',
                                                        					20=>'20',
                                                        					30=>'30',
                                                        					50=>'50',
                                                        					100=>'100',
                                                        					200=>'200');
                                                        	if($ssFilter['pagging']=='')
                                                        		$ssFilter['pagging']=20;
															$numPerPage = $this->formSelect('pagging',$ssFilter['pagging'],
																							array('onchange'=>"OnSubmitForm('" . $linkSlbPagging . "')"),
																							$options);
															echo 'Items per page:'.$numPerPage;
                                                        ?>
                                                        <div class="limit"></div>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>					
                                    </tfoot>				<!-- END: PAGINATION (FOOT) -->
                                </table>
                                <!-- Area 4: In du lieu lay tu database - End -->

                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>