<?php 
//'id','name','phone','email','created','created_by','status'
	
    $id 		= $this->Item['id'];
    $name 		= $this->Item['name'];
    $phone 		= $this->Item['phone'];
    $email 		= $this->Item['email'];
    $created 	= $this->Item['created'];
    $status 	= $this->Item['status'];
    
    $htmlListProduct='<table class="adminlist">';
    $htmlListProduct.='<thead><tr>
        <th width="50">ID</th>
        <th width="120">Hình ảnh</th>
        <th>Tên sản phẩm</th>
        <th width="100">Số lượng</th>
        <th width="150">Đơn giá</th>
        <th width="150">Thành tiền</th>
    </tr><thead><tbody>';
    $sum=0;
    foreach($this->ListProduct as $key=>$info)
    {
        $t=$info['price']*$info['quantity'];
        $sum+=$t;
        $product_image	= PUBLIC_URL.'/files/products/image/'.$info['image'];
        $linkPro=$this->baseUrl('product/admin-product/edit/id/'.$info['pro_id']);
        $htmlListProduct.='<tr>
                <th align="center"><a href="'.$linkPro.'">'.$info['id'].'</a></th>
                <td><a href="'.$linkPro.'"><img src="'.$product_image.'" width="120"></a></td>
                <td><a href="'.$linkPro.'">'.$info['name'].'</a></td>
                <td align="center">'.$info['quantity'].'</td>
                <td align="center">'.number_format($info['price']).'</td>
                <td align="center">'. number_format($t).'</td>
        </tr>
        ';
    }
    
    
    $htmlListProduct.='</tbody><tfoot><td></td><td></td><td></td><td></td><th>Tổng giá trị</th><td>'.number_format($sum).'</td></tfoot></table>';
?>
<form name="appForm" method="post" action="">



                        <?php echo $this->render('admin-product-order/toolbar/index.php')?>
                        <div class="clr"></div>
                         <?php echo $this->render('admin-product-order/sublink/index.php')?>

                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
						<div id="adminfieldset">
                             <div class="adminheader">Chi tiết đơn hàng</div>
								<div id="row">
                                    <div class="label">Mã đơn đặt hàng:</div>
                                    <?php echo $id;?>			
                                </div>
                                <div class="clr"></div>
								<div id="row">
                                    <div class="label">Họ tên:</div>
                                    <?php echo $name;?>			
                                </div>
                                <div class="clr"></div>
                                <div id="row">
                                    <div class="label">Số điện thoại:</div>
                                    <?php echo $phone;?>			
                                </div>
                                <div class="clr"></div>
                                <div id="row">
                                    <div class="label">Ngày đặt hàng:</div>
                                    <?php echo $created;?>			
                                </div>
                                <div class="clr"></div>
                                <div id="row">
                                    <div class="label">Trạng thái:</div>
                                    <?php echo ($status)?'Đã xử lý':'Chưa xử lý';?>			
                                </div>
                                <div class="clr"></div>
                                
                                <div class="clr"></div>
                                <div id="row">
                                    <div class="label">Danh sách sản phẩm</div>
                                    <div class="clr"></div>
                                    <?php echo $htmlListProduct;?>			
                                </div>
                                <div class="clr"></div>
                                
							</div>
							
                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>