<?php 
	
	$ssFilter = $this->arrParam['ssFilter'];
	$action_link 	= $this->baseUrl($this->currentController . '/filter/type/order');
	$lblTitle 	= $this->cmsLinkSort('Name','n.name',$ssFilter,
										$this->imgUrl . '/icon',$action_link);
	
	$lblStatus		= $this->cmsLinkSort('In Home Page','n.status',$ssFilter,
										$this->imgUrl . '/icon',$action_link);											
	$lblOrder		= $this->cmsLinkSort('Order','n.order',$ssFilter,
										$this->imgUrl . '/icon',$action_link);
	$lblCreated= $this->cmsLinkSort('Created','n.created',$ssFilter,
										$this->imgUrl . '/icon',$action_link);
										
	$lblCat 		= $this->cmsLinkSort('Category','cat_name',$ssFilter,
										$this->imgUrl . '/icon',$action_link);																	

	$lblID 		= $this->cmsLinkSort('ID','n.id',$ssFilter,
										$this->imgUrl . '/icon',$action_link);

	//-------------------CREATE CATEGORY SELECTBOX ------------------------
	$linkSlbCategory = $this->baseUrl($this->currentController . '/filter/type/category');
	$options = $this->listCat;	
	$slbCategory = $this->cmsCategorySelect('cat_id',$ssFilter['cat_id'],$options,array('onchange'=>"OnSubmitForm('" . $linkSlbCategory . "')"));
	$selectCategory = ' - Category: ' . $slbCategory;
	
   
    //danh sach dia diem
    $linkSlbLocation = $this->baseUrl($this->currentController . '/filter/type/location');
    $options = $this->listLocation;	
	$slbLocation = $this->cmsCategorySelect('district_id',$ssFilter['district_id'],$options,array('onchange'=>"OnSubmitForm('" . $linkSlbLocation . "')"));	
    $selectLocation = ' - Location: ' . $slbLocation;
    
	//-------------------CREATE DATE FILTER ------------------------
	$dateFrom	= '  -  Date from: '.$this->cmsDatepicker('date_from',$ssFilter['date_from'],array('class'=>'txtshort'), $this,'birthday');
	$dateTo		= ' - Date to: '.$this->cmsDatepicker('date_to',$ssFilter['date_to'],array('class'=>'txtshort'), $this,'birthday');
	$linkSearch = $this->baseUrl($this->currentController . '/filter/type/date/key/1');
	$btnSearch = $this->formButton('search-now','Filter by date',
									array('onclick'=>"OnSubmitForm('" . $linkSearch . "')"));
	$linkResetSearch = $this->baseUrl($this->currentController . '/filter/type/date/key/0');							
	$btnResetSearch = $this->formButton('clear-keywords','Show all',
									array('onclick'=>"OnSubmitForm('" . $linkResetSearch . "')"));
	$strDateSearch = $dateFrom . ' ' . $dateTo . ' ' . $btnSearch . ' ' . $btnResetSearch;	
	
	//CREATE SEARCH AREA
	$keywords = $this->formText('keywords',$ssFilter['keywords'],array('class'=>'txtshort'));
	$linkSearch = $this->baseUrl($this->currentController . '/filter/type/search/key/1');
	$btnSearch = $this->formButton('search-now','Search now',
									array('onclick'=>"OnSubmitForm('" . $linkSearch . "')"));
	$linkResetSearch = $this->baseUrl($this->currentController . '/filter/type/search/key/0');							
	$btnResetSearch = $this->formButton('clear-keywords','Clear',
									array('onclick'=>"OnSubmitForm('" . $linkResetSearch . "')"));	
	 $strSearch = $keywords . ' ' . $btnSearch . ' ' . $btnResetSearch;	
	 $this->view->errors;															
?>
<form name="appForm" method="post" action="">



                        <?php echo $this->render('admin-product-special/toolbar/index.php')?>
                        <div class="clr"></div>
                         <?php echo $this->render('admin-product-special/sublink/index.php')?>

                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
								<div id="filters">
									<div style="float:left;">
										<?php echo $strSearch . $strDateSearch;?>
									</div>
									<div  style="float:right;">
										<?php echo $selectCategory;?>
                                        <?php echo $selectLocation;?>
									</div>
									<div class="clr"></div>
								</div>	

                                <!-- Area 4: In du lieu lay tu database -->
                                <table class="adminlist">
                                    <thead>
                                        <tr>
                                            <th width="43" >
                                            	<input type="checkbox" name="checkbox" id="checkbox" onclick="checkedAll()">
                                           	</th>
                                            <th><?php echo $lblTitle;?></th>
                                            <th width="89"><?php echo $lblStatus;?></th>                                           
                                            <th width="200"><?php echo $lblCreated;?></th>						
                                            <th width="200"><?php echo $lblCat;?></th>
                                            <th width="77"><?php echo $lblOrder;?></th>
                                            <th width="90">Control</th>

                                            <th width="34"><?php echo $lblID;?></th>
                                        </tr>
                                    </thead>
									<?php 
										foreach($this->Items as $key => $val){
											$id 			= $val['id'];
											$name			= $val['name'];
											
											$created 		= $val['created'];
											$cat_name 		= $val['cat_name'];
											
											$status 		= $val['status'];
											if($status == 1){	
												$linkStatus = $this->baseUrl($this->currentController . '/status/type/0/id/' . $id . '/page/' . $this->arrParam['page']);											
												$status = $this->cmsIconButton('Active', $this->imgUrl . '/icon/active.png',$linkStatus);
											}else{
												$linkStatus = $this->baseUrl($this->currentController . '/status/type/1/id/' . $id . '/page/' . $this->arrParam['page']);
												$status = $this->cmsIconButton('INactive', $this->imgUrl . '/icon/inactive.png',$linkStatus);
											}											
											
											
											
											$order 			= $this->formText('order[' . $val['id'] . ']' ,$val['order'],array('style'=>'width: 30px; text-align: center;'));
											
											$linkInfo		= $this->baseUrl($this->currentController . '/info/id/' . $id);											
											$btnInfo		= $this->cmsIconButton('View Item',$this->imgUrl . '/icon_info.png',$linkInfo);
											
											$linkEdit		= $this->baseUrl($this->currentController . '/edit/id/' . $id);
											$btnEdit		= $this->cmsIconButton('Edit Item',$this->imgUrl . '/icon_edit.png',$linkEdit);
											
											$linkDelete		= $this->baseUrl($this->currentController . '/delete/id/' . $id);
											$btnDelete		= $this->cmsIconButton('Delete Item',$this->imgUrl . '/icon_del.png',$linkDelete);
										
											$strIconButton	= $btnInfo . ' ' . $btnEdit . ' ' . $btnDelete;
											
											$cid			= $this->formCheckbox('cid[]',$val['id']);
									?>
                                    <tr class="even">						
                                        <td align="center"><?php echo $cid;?></td>
                                        <td align="left"><?php echo $name;?></td>
                                        <td align="center"><?php echo $status;?></td>                                        
                                        <td align="center"><?php echo $created;?></td>
                                        <td align="center"><?php echo $cat_name;?></td>
                                        <td align="center"><?php echo $order;?></td>
                                        <td align="center"><?php echo $strIconButton;?></td>
                                        <td align="center"><?php echo $id;?></td>
                                    </tr>
                                    <?php 
										}
										
                                    ?>
                                    <!-- BEGIN: PAGINATION (FOOT) -->
                                    <tfoot>
                                        <tr>
                                            <td colspan="9">
                                                <div class="container">
                                                    <div class="pagination">
                                                        <?php 
                                                        	$currentUrl = $this->baseUrl($this->currentController . '/index');
                                                        	echo $this->paginationControl($this->panigator,'Sliding','pagination.phtml',array('currentUrl'=>$currentUrl));
                                                        	
                                                        	// display items per page
                                                        	$linkSlbPagging = $this->baseUrl($this->currentController . '/filter/type/pagging');
                                                        	$options = array(5=>'5',
                                                        					10=>'10',
                                                        					20=>'20',
                                                        					30=>'30',
                                                        					50=>'50',
                                                        					100=>'100',
                                                        					200=>'200');
                                                        	if($ssFilter['pagging']=='')
                                                        		$ssFilter['pagging']=20;
															$numPerPage = $this->formSelect('pagging',$ssFilter['pagging'],
																							array('onchange'=>"OnSubmitForm('" . $linkSlbPagging . "')"),
																							$options);
															echo 'Items per page:'.$numPerPage;
                                                        ?>
                                                        <div class="limit"></div>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>					
                                    </tfoot>				<!-- END: PAGINATION (FOOT) -->
                                </table>
                                <!-- Area 4: In du lieu lay tu database - End -->

                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>