<?php 

	
	$title 			= $this->formText('title',$this->Item['title'],array('class'=>'txtmedium'));
	$summary 		= $this->cmsEditor('summary',$this->cmsConvertDbToView($this->Item['summary']),$width = '100%',$height = 200,'basic');

	$news_image		= '<img src="'.PUBLIC_URL.'/files/weblink/logo/'.$this->Item['full_image'].'">';
	$image         = $this->formFile('full_image',array('style'=>'width: 250px'));
    $image_current  = $this->formHidden('image_current',$this->Item['image']);
    $link          = $this->formText('link',$this->Item['title'],array('class'=>'txtmedium'));
    
    $options        = array('No','Yes');
    $is_hot             = $this->formRadio('is_hot',$this->Item['is_hot'],null,$options, ' ');



    $options        = array('No','Yes');
    $is_home            = $this->formRadio('is_home',$this->Item['is_home'],null,$options, ' ');
	$options 		= array('Inactive','Active');
	$status 		= $this->formRadio('status',$this->Item['status'],null,$options, ' ');
	
	$options 		= array('Enable','Disable');
	$comment 		= $this->formRadio('comment',$this->Item['comment'],null,$options, ' ');
	
	$options        = $this->listCat;	
	$listCat        = $this->cmsCategorySelect('cat_id',$this->Item['cat_id'],$options,array('style'=>'width:255px','onChange'=>'updateAlbumByCat();'));
    	
	$options        = $this->listAlbum;	
                    
    
	$listAlbum        = $this->cmsCategorySelect('album_id',$this->Item['album_id'],$options,array('style'=>'width:255px'));	
	
	$order			= $this->formText('order',$this->Item['order'],array('class'=>'txtmedium'));
	
	$created		= $this->Item['created'];
	$created_by		= $this->Item['created_by'];
	$modified		= $this->Item['modified'];
	$modified_by	= $this->Item['modified_by'];
	$hit			= $this->Item['hit'];
	
	//------------------- PRINT ERRORS ------------------------
	if(!empty($this->errors)){
		$errors = $this->formErrors($this->errors );
	}
?>
<script>
function updateAlbumByCat()
{
    var cat_id = $('select[name=cat_id]').val();
    var album_id = $('select[name=cat_id]').val();   
    $.ajax({
          url:'<?php echo $this->baseUrl($this->currentController . '/getalbum/'); ?>' ,
          data: {'cat_id':cat_id,'album_id':album_id},
          success: function(data){
            if(data)
            {
                if($(data).html())
                {
                    $('select[name=album_id]').html($(data).html());     
                }
                else
                {
                    $('select[name=album_id]').html('<option value="0">None</option>');
                }                
            }
           
          }          
        });  
}

</script>
<form name="appForm" method="post" action="" enctype="multipart/form-data">


                        <?php echo $this->render('admin-weblink/toolbar/index.php')?>
                        <div class="clr"></div>
                         <?php echo $this->render('admin-weblink/sublink/index.php')?>

                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
						<div id="adminfieldset">
                             <div class="adminheader">Detail</div>
										
                         		<?php 
                         		if(!empty($this->errors)){
                         			if($this->errors[0]=="success"){
                         				echo '<div id="success">';
										echo '<pre>';
											print_r($errors);
										echo '</pre>';
										echo '</div>';
                         				
                         			}
                         			else{
	                         			echo '<div id="errors">';
										echo '<pre>';
											print_r($errors);
										echo '</pre>';
										echo '</div>';
                         			}
								}
                         		
								?>
								
								<div id="row">
                                    <div class="label">Title:</div>
                                    <?php echo $title;?>			
                                </div>
                                <div class="clr"></div>
                                
                                <div id="row">
                                    <div class="label">Image:</div>
                                    <?php echo $news_image;?>
                                    <?php echo $image_current;?>                                    
                                    <?php echo $image;?>
                                    		
                                </div>
                                <div class="clr"></div>

                                <div id="row">
                                    <div class="label">Link:</div>
                                    <?php echo $link;?>           
                                </div>
                                <div class="clr"></div>

                                <div id="row">
                                    <div class="label">Hot:</div>
                                    <?php echo $is_hot;?>           
                                </div>
                                <div class="clr"></div>
                                
                                <div id="row">
                                    <div class="label">Home:</div>
                                    <?php echo $is_home;?>          
                                </div>
                                <div class="clr"></div>
                                

                                <div id="row">
                                    <div class="label">Status:</div>
                                    <?php echo $status;?>			
                                </div>
                                <div class="clr"></div>
                                
                                <!--div id="row">
                                    <div class="label">Comment:</div>
                                    <?php echo $comment;?>			
                                </div-->
                                <div class="clr"></div>
                                
                                <div id="row">
                                    <div class="label">Category:</div>
                                    <?php echo $listCat;?>			
                                </div>
                                <div class="clr"></div>
                               
                                <div id="row">
                                    <div class="label">Order:</div>
                                    <?php echo $order;?>			
                                </div>
                                <div class="clr"></div>
                                
                                <div id="row">
                                    <div class="label">Hit:</div>
                                    <?php echo $hit;?>			
                                </div>
                                <div class="clr"></div>
                                 <div id="row">
                                    <div class="label">Created:</div>
                                    <?php echo $created;?>			
                                </div>
                                <div class="clr"></div>
                                
                                <div id="row">
                                    <div class="label">Created by:</div>
                                    <?php echo $created_by;?>			
                                </div>
                                <div class="clr"></div>
                                
                                <div id="row">
                                    <div class="label">Modified:</div>
                                    <?php echo $modified;?>			
                                </div>
                                <div class="clr"></div>
                                
                                <div id="row">
                                    <div class="label">Modified by:</div>
                                    <?php echo $modified_by;?>			
                                </div>
                                <div class="clr"></div>
                                                       
                                <div id="row">
                                    <div class="label">Summary:</div>
                                    <div class="clr"></div>
                                    <?php echo $summary;?>	
                                    		
                                </div>
                                <div class="clr"></div>
                                
                               
                                
							</div>
							
                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>