<?php
	$selectKhuvuc='<label for="khuvuc">Khu vực</label><select name="khuvuc" id="khuvuc">';
	$selectTinh='<label for="tinh">Tinh</label><select name="tinh" id="tinh">';
	foreach ($this->listLocation as $key => $value) {
		$selectKhuvuc.='<option value="'.$key.'">'.$value['khuvuc'].'</option>';

		foreach ($value['citys'] as $k => $v) {
			$selectTinh.='<option value="'.$k.'" location="'.$key.'">'.$v.'</option>';
		}
		
	}
	$selectKhuvuc.='</select>';
	$selectTinh.='</select>';


?>
<div data-role="page" class="jqm-demos ui-responsive-panel" id="panel-fixed-thoitiet">

    <div data-role="header"   data-position="fixed" data-theme="c" >
        <h1>Thời tiết</h1>
        <a href="#nav-panel" data-icon="bars" data-iconpos="notext">Menu</a>
    </div><!-- /header -->

    <div data-role="content" class="jqm-content">
		<form>
		<fieldset data-role="controlgroup" data-type="horizontal" data-mini="true">
		    <legend>Bạn hãy chọn khu vực cần xem</legend>
		    <?php echo $selectKhuvuc;?>
		    <?php echo $selectTinh;?>
		</fieldset>
		</form>
		<div id="thoitiet-content"></div>
    </div><!-- /content -->

	<div data-role="panel" data-position="left" data-position-fixed="false" data-theme="c" id="nav-panel">

		<form>
		     <label for="search-1">Tìm kiếm trang của bạn</label>
		     <input name="search-1" id="search-1" value="" type="search">
		</form>

		<div data-role="collapsible-set" data-inset="false" data-iconpos="left" data-collapsed-icon="plus" data-expanded-icon="minus" data-theme="b">
		    <div data-role="collapsible" data-transition="slidedown" data-collapsed="false">
		        <h3>Tin tức</h3>
		        <ul data-role="listview" data-inset="false">
		            <li><a href="#panel-fixed-page2" data-transition="slide">Thể thao</a></li>
		            <li><a href="#panel-fixed-page2" data-transition="slide">Thời sự</a></li>
		            <li><a href="#panel-fixed-page2" data-transition="slide">Sao 24h</a></li>
		            <li><a href="#panel-fixed-page2" data-transition="slide">Thế giới</a></li>
		        </ul>
		    </div>
		    <div data-role="collapsible">
		        <h3>Cars</h3>
		        <ul data-role="listview" data-inset="false" >
		            <li><a href="#panel-fixed-page2" data-transition="slide">Acura</a></li>
		            <li><a href="#panel-fixed-page2" data-transition="slide">Audi</a></li>
		            <li><a href="#panel-fixed-page2" data-transition="slide">BMW</a></li>
		            <li><a href="#panel-fixed-page2" data-transition="slide">Cadillac</a></li>
		        </ul>
		    </div>
		    <div data-role="collapsible">
		        <h3>Game</h3>
		        <ul data-role="listview" data-inset="false" >
		            <li><a href="#panel-fixed-page2" data-transition="slide">Offline</a></li>
		            <li><a href="#panel-fixed-page2" data-transition="slide">Online</a></li>
		            <li><a href="#panel-fixed-page2" data-transition="slide">Game flash</a></li>
		        </ul>
		    </div>
		    <div data-role="collapsible">
		        <h3>Tin tức</h3>
		        <ul data-role="listview" data-inset="false" >
		            <li><a href="#panel-fixed-page2" data-transition="slide">Thể thao</a></li>
		            <li><a href="#panel-fixed-page2" data-transition="slide">Thời sự</a></li>
		            <li><a href="#panel-fixed-page2" data-transition="slide">Sao 24h</a></li>
		            <li><a href="#panel-fixed-page2" data-transition="slide">Thế giới</a></li>
		        </ul>
		    </div>
		    <div data-role="collapsible">
		        <h3>Cars</h3>
		        <ul data-role="listview" data-inset="false" >
		            <li><a href="#panel-fixed-page2" data-transition="slide">Acura</a></li>
		            <li><a href="#panel-fixed-page2" data-transition="slide">Audi</a></li>
		            <li><a href="#panel-fixed-page2" data-transition="slide">BMW</a></li>
		            <li><a href="#panel-fixed-page2" data-transition="slide">Cadillac</a></li>
		        </ul>
		    </div>
		    <div data-role="collapsible">
		        <h3>Game</h3>
		        <ul data-role="listview" data-inset="false" >
		            <li><a href="#panel-fixed-page2" data-transition="slide">Offline</a></li>
		            <li><a href="#panel-fixed-page2" data-transition="slide">Online</a></li>
		            <li><a href="#panel-fixed-page2" data-transition="slide">Game flash</a></li>
		        </ul>
		    </div>
		</div>
	</div><!-- /panel -->
</div><!-- /page -->
