<?php 
	$license		= $this->cmsEditor('lienhe',$this->cmsConvertDbToView($this->Item['lienhe']),$width = '100%',$height = 300);
	if(!empty($this->errors)){
		$errors = $this->formErrors($this->errors );
	}
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">



                        <?php echo $this->render('admin-content/toolbar/index.php')?>
                        <div class="clr"></div>
                         <?php echo $this->render('admin-content/sublink/index.php')?>

                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
						<div id="adminfieldset">
                             <div class="adminheader">Detail</div>
										
                         		<?php 
                         		if(!empty($this->errors)){
                         			if($this->errors[0]=="success"){
                         				echo '<div id="success">';
										echo '<pre>';
											print_r($errors);
										echo '</pre>';
										echo '</div>';
                         				
                         			}
                         			else{
	                         			echo '<div id="errors">';
										echo '<pre>';
											print_r($errors);
										echo '</pre>';
										echo '</div>';
                         			}
								}
                         		
								?>
								
								<div id="row">
                                    <div class="label">Liên hệ :</div>
                                    <?php echo $license;?>			
                                </div>
                                <div class="clr"></div>
                                
							</div>
							
                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>