<?php 
	$name 		= $this->Item['name'];
	$parent_name= $this->Item['parent_name'];
	$order		= $this->Item['order'];
	$status		= $this->Item['status'];
?>
<form name="appForm" method="post" action="">



                        <?php echo $this->render('admin-product-category/toolbar/index.php')?>
                        <div class="clr"></div>
                         <?php echo $this->render('admin-product-category/sublink/index.php')?>

                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
						<div id="adminfieldset">
                             <div class="adminheader">Item Detail</div>
								
								<div id="row">
                                    <div class="label">Category name:</div>
                                    <?php echo $name;?>			
                                </div>
                                <div class="clr"></div>
                                <div id="row">
                                    <div class="label">Category parent:</div>
                                    <?php echo $parent_name;?>			
                                </div>
                                <div class="clr"></div>
                                <div id="row">
                                    <div class="label">Order:</div>
                                    <?php echo $order;?>			
                                </div>
                                <div class="clr"></div>
                                <div id="row">
                                    <div class="label">Status:</div>
                                    <?php echo $status;?>			
                                </div>
                                <div class="clr"></div>
                                
                                
							</div>
							
                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>