<div class="clear"></div>
<div id="wrapper">
    <div id="content">
        <div id="content-left">
            <div id="left-content">
                <div id="entries-content" style="padding: 20px !important;">
                    <h1 style="font-size: 21px;font-weight: bold;margin: 0 0 20px;">Nội quy đăng bài lên ShockVL</h1>
                    <?php echo $this->Item['noiquy'];?>
                </div>
            </div>
        </div>
        <div id="content-right">
            <div id="side-bar">
                <?php echo $this->ShowSidebar($this,'noiquy');?>
            </div>    
        </div>
    </div>
</div>