<?php 

	
	$title 			= $this->formText('title',$this->Item['title'],array('class'=>'txtmedium'));
	$summary 		= $this->cmsEditor('summary',$this->cmsConvertDbToView($this->Item['summary']),$width = '100%',$height = 200,'basic');
	$content		= $this->cmsEditor('content',$this->cmsConvertDbToView($this->Item['content']),$width = '100%',$height = 500);
	
	$image			= $this->formFile('image',array('style'=>'width: 250px'));
	//$image_current	= $this->formHidden('image_current',$this->Item['image']);
	
	$news_image		= '<img src="'.PUBLIC_URL.'/files/news/100x100/'.$this->Item['image'].'">';
	
	$options 		= array('No','Yes');
	$hot 			= $this->formRadio('hot',$this->Item['hot'],null,$options, ' ');
	
	$options 		= array('Inactive','Active');
	$status 		= $this->formRadio('status',$this->Item['status'],null,$options, ' ');
	
	$options 		= array('Enable','Disable');
	$comment 		= $this->formRadio('comment',$this->Item['comment'],null,$options, ' ');
		
	$options = $this->listCat;	
	$listCat = $this->cmsCategorySelect('cat_id',$this->Item['cat_id'],$options,array('style'=>'width:255px'));	
	
	$order			= $this->formText('order',$this->Item['order'],array('class'=>'txtmedium'));
	
	
	
	
	

	
	//------------------- PRINT ERRORS ------------------------
	if(!empty($this->errors)){
		$errors = $this->formErrors($this->errors );
	}
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">



                        <?php echo $this->render('admin-product/toolbar/index.php')?>
                        <div class="clr"></div>
                         <?php echo $this->render('admin-product/sublink/index.php')?>

                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
						<div id="adminfieldset">
                             <div class="adminheader">Detail</div>
										
                         		<?php 
                         		if(!empty($this->errors)){
                         			if($this->errors[0]=="success"){
                         				echo '<div id="success">';
										echo '<pre>';
											print_r($errors);
										echo '</pre>';
										echo '</div>';
                         				
                         			}
                         			else{
	                         			echo '<div id="errors">';
										echo '<pre>';
											print_r($errors);
										echo '</pre>';
										echo '</div>';
                         			}
								}
                         		
								?>
								
								<div id="row">
                                    <div class="label">Title:</div>
                                    <?php echo $title;?>			
                                </div>
                                <div class="clr"></div>
                                
                                <div id="row">
                                    <div class="label">Image:</div>
                                    <?php echo $image.'<br />'.$news_image;?>			
                                </div>
                                <div class="clr"></div>
                                
                                <div id="row">
                                    <div class="label">Hot:</div>
                                    <?php echo $hot;?>			
                                </div>
                                <div class="clr"></div>
                                
                                <div id="row">
                                    <div class="label">Status:</div>
                                    <?php echo $status;?>			
                                </div>
                                <div class="clr"></div>
                                
                                <div id="row">
                                    <div class="label">Comment:</div>
                                    <?php echo $comment;?>			
                                </div>
                                <div class="clr"></div>
                                
                                <div id="row">
                                    <div class="label">Category:</div>
                                    <?php echo $listCat;?>			
                                </div>
                                <div class="clr"></div>
                                
                                <div id="row">
                                    <div class="label">Order:</div>
                                    <?php echo $order;?>			
                                </div>
                                <div class="clr"></div>
                                                        
                                <div id="row">
                                    <div class="label">Summary:</div>
                                    <div class="clr"></div>
                                    <?php echo $summary;?>	
                                    		
                                </div>
                                <div class="clr"></div>
                                
                                <div id="row">
                                    <div class="label">Content:</div>
                                    <div class="clr"></div>
                                    <?php echo $content;?>			
                                </div>
                                <div class="clr"></div>
                                
							</div>
							
                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>