<?php 

	$ssFilter = $this->arrParam['ssFilter'];
	$action_link 	= $this->baseUrl($this->currentController . '/filter/type/order');
	$lblName 	= $this->cmsLinkSort('Title','ncm.full_name',$ssFilter,
										$this->imgUrl . '/icon',$action_link);
	
	$lblStatus		= $this->cmsLinkSort('Status','ncm.status',$ssFilter,
										$this->imgUrl . '/icon',$action_link);											
	$lblCreated= $this->cmsLinkSort('Created','ncm.created',$ssFilter,
										$this->imgUrl . '/icon',$action_link);
										
	$lblProduct= $this->cmsLinkSort('Product name','n.name',$ssFilter,
										$this->imgUrl . '/icon',$action_link);
																								

	$lblID 		= $this->cmsLinkSort('ID','ncm.id',$ssFilter,
										$this->imgUrl . '/icon',$action_link);
	//CREATE BUTTON RESET
	$linkResetItem = $this->baseUrl($this->currentController . '/filter/type/item_id/key/0');							
	$btnResetItem = $this->formButton('clear-item','View All Comment',
									array('onclick'=>"OnSubmitForm('" . $linkResetItem . "')"));	
	
	
	 $this->view->errors;															
?>
<form name="appForm" method="post" action="">



                        <?php echo $this->render('admin-product-comment/toolbar/index.php')?>
                        <div class="clr"></div>
                         <?php echo $this->render('admin-product-comment/sublink/index.php')?>

                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
								<div id="filters">
									<div style="float:left;">
										
									</div>
									<div  style="float:right;">
										<?php echo $btnResetItem;?>
									</div>
									<div class="clr"></div>
								</div>	

                                <!-- Area 4: In du lieu lay tu database -->
                                <table class="adminlist">
                                    <thead>
                                        <tr>
                                            <th width="43" >
                                            	<input type="checkbox" name="checkbox" id="checkbox" onclick="checkedAll()">
                                           	</th>
                                            <th><?php echo $lblName;?></th>
                                            <th width="89"><?php echo $lblStatus;?></th>                                           
                                            <th width="200"><?php echo $lblCreated;?></th>  
                                            <th width="200"><?php echo $lblProduct;?></th>  
                                            <th width="90">Control</th>

                                            <th width="34"><?php echo $lblID;?></th>
                                        </tr>
                                    </thead>
									<?php 
										foreach($this->Items as $key => $val){
											$id 			= $val['id'];
											$full_name		= $val['full_name'];
											$product_name	= $val['product_name'];
											$content		= $val['content'];
											$created 		= $val['created'];
											$status 		= $val['status'];
											if($status == 1){	
												$linkStatus = $this->baseUrl($this->currentController . '/status/type/0/id/' . $id . '/page/' . $this->arrParam['page']);											
												$status = $this->cmsIconButton('Active', $this->imgUrl . '/icon/active.png',$linkStatus);
											}else{
												$linkStatus = $this->baseUrl($this->currentController . '/status/type/1/id/' . $id . '/page/' . $this->arrParam['page']);
												$status = $this->cmsIconButton('INactive', $this->imgUrl . '/icon/inactive.png',$linkStatus);
											}											
											
											
											
											$linkDelete		= $this->baseUrl($this->currentController . '/delete/id/' . $id);
											$btnDelete		= $this->cmsIconButton('Delete Item',$this->imgUrl . '/icon_del.png',$linkDelete);
										
											$strIconButton	=  $btnDelete;
											
											$cid			= $this->formCheckbox('cid[]',$val['id']);
									?>
                                    <tr class="even">						
                                        <td align="center"><?php echo $cid;?></td>
                                        <td align="left"><?php echo '<b>'.$full_name .'</b><br />' . $content;?></td>
                                        <td align="center"><?php echo $status;?></td>                                        
                                        <td align="center"><?php echo $created;?></td>                                        
                                        <td align="center"><?php echo $product_name;?></td>                                        
                                        <td align="center"><?php echo $strIconButton;?></td>
                                        <td align="center"><?php echo $id;?></td>
                                    </tr>
                                    <?php 
										}
										
                                    ?>
                                    <!-- BEGIN: PAGINATION (FOOT) -->
                                    <tfoot>
                                        <tr>
                                            <td colspan="9">
                                                <div class="container">
                                                    <div class="pagination">
                                                        <?php 
                                                        	$currentUrl = $this->baseUrl($this->currentController . '/index');
                                                        	echo $this->paginationControl($this->panigator,'Sliding','pagination.phtml',array('currentUrl'=>$currentUrl));
                                                        	
                                                        	// display items per page
                                                        	$linkSlbPagging = $this->baseUrl($this->currentController . '/filter/type/pagging');
                                                        	$options = array(5=>'5',
                                                        					10=>'10',
                                                        					20=>'20',
                                                        					30=>'30',
                                                        					50=>'50',
                                                        					100=>'100',
                                                        					200=>'200');
                                                        	if($ssFilter['pagging']=='')
                                                        		$ssFilter['pagging']=20;
															$numPerPage = $this->formSelect('pagging',$ssFilter['pagging'],
																							array('onchange'=>"OnSubmitForm('" . $linkSlbPagging . "')"),
																							$options);
															echo 'Items per page:'.$numPerPage;
                                                        ?>
                                                        <div class="limit"></div>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>					
                                    </tfoot>				<!-- END: PAGINATION (FOOT) -->
                                </table>
                                <!-- Area 4: In du lieu lay tu database - End -->

                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>