<?php
	//router key
	$action='article-index-index-'.$this->orderType.'-page';
	
	$linkPrevious = 'javascript:void(0);';
	$disabledNext=$disabledPrev = 'disabled';
	if(isset($this->previous)){

		
		$linkPrevious 	= $this->serverUrl($this->url(array('page'=>$this->previous),$action));

		//$linkPrevious 	= $this->currentUrl . '/' . $this->previous;
		$disabledPrev='';
	}
	$linkNext = 'javascript:void(0);';
	if(isset($this->next)){
		//$linkNext 		= $this->currentUrl . '/' . $this->next;
		$linkNext = $this->serverUrl($this->url(array('page'=>$this->next),$action));
		$disabledNext='';
	}

?>



<div id="paging-buttons" class="paging-buttons">
    <a class="buttons prevListPage <?php echo $disabledPrev;?>" href="<?php echo $linkPrevious;?>">« Quay lại</a>
    <a class="buttons nextListPage <?php echo $disabledNext;?>"  href="<?php echo $linkNext;?>">Xem tiếp »</a>
</div>