<?php
	
	$listLocation = $this->listLocation;
    //echo count($listLocation);
    
	$selectTinh='<label for="tinh"><strong>Thành phố</strong>: </label><select onChange="showCityXoso(this.value)" name="tinh" id="tinh">';
	foreach ($this->listLocation as $k => $v) {
		$selectTinh.='<option value="'.$k.'">'.$v.'</option>';	
     
	}
	$selectTinh.='</select>';

	$xoso='';
    $arrDefaultShow = array('1');
	foreach ($this->xoso as $key => $value) 
	{
	    if(in_array($key,$arrDefaultShow))
        {
            $strShow ='';
        }
        else
        {
            $strShow ='style="display:none"';
        }
        $xoso .= '<div class="xoso-list-city" id="xoso-list-'.$key.'" '.$strShow.'>';
        
        
        $strInfo .= '<span '.$strShow.' id="xoso-info-'.$key.'">KẾT QUẢ XỔ SỐ '. mb_strtoupper($listLocation[$key],'UTF-8').'</span>';
        foreach($value as $k => $v)
        {
            $xoso.= $v;
            
        }
        
        $xoso .= '</div>';
	}

?>
<script>

$(document).ready(function(){
	$("#tinh").change(function(){
		var idTinh=$(this).val();
		$(".thoitietinfo").hide();
		//$("#tinh_header_"+idTinh).show();
		$("#tinh_body_"+idTinh).show();
	});
	$("#tinh").change();
});

function showCityXoso(id)
{
	
    $('.xoso-list-city').hide();
    $('.xoso-title span').hide();
    var showID = '#xoso-list-'+id;
    var infoID = '#xoso-info-'+id;
    $(showID).fadeIn(1000);
    $(infoID).fadeIn(1000);
}
</script>

<div data-role="page" class="jqm-demos ui-responsive-panel" id="panel-fixed-thoitiet">

    <div data-role="header" data-theme="c" >
        <h1>Kết quả xổ số</h1>
        <?php echo $this->showCategory($this);?>
        <a href="<?php echo $this->baseUrl('');?>" data-icon="home" data-iconpos="notext" data-transition="slide">Home</a>
    </div><!-- /header -->

    <div data-role="content" class="jqm-content">
		<form>
		<fieldset data-role="controlgroup" data-type="horizontal" data-mini="true">
		    <legend>Tỉnh thành </legend>
		    <?php //echo $selectKhuvuc;?>
		    <?php echo $selectTinh;?>
		</fieldset>
		</form>
		
		  <?php echo $xoso;?>
		
    </div><!-- /content -->

	
	<?php echo $this->showCategory($this,'service');?>
	
</div><!-- /page -->
